### ISSUE TITLE
Look at integrating SilenceIM/Textsecure methods for Pony SMS encryption

### ISSUE THREAD

**Issue by amicrod** [Samourai-Wallet/samourai-wallet-android#100]
Silence messenger uses OTR techniques to hide SMS details.  Perhaps this would be useful privacy consideration with the new pony feature.  Thanks for your hard work!

https://github.com/SilenceIM/Silence

**Comment by SamouraiDev** [comment]
Pony Direct is not a feature of Samourai Wallet but a separate app. https://github.com/MuleTools/PonyDirect Please post the comment there so we can track it. Thank you.
