### ISSUE TITLE
Binarys in source tree

### ISSUE THREAD

**Issue by taaem** [Samourai-Wallet/samourai-wallet-android#102]
Hello,

I'd like to ask why you have _compiled_ binarys in your source code tree?
Why not include instructions how to build/get these?

From a user point of view eventthough the app is opensource you _could_ be injecting malicious code inside of these binarys.

Specifically I'm talking about the libs in app/libs and app/src/main/jniLibs, which can't be looked at. 

I'd wish to know where these come from and how to build them myself. I'm not saying that it's bad to have them compiled in the tree, it definitly makes building for users much easier since they just need to import to Android Studio or build via gradle, but I think if you want to be a popular _open source_ Bitcoin Wallet anyone should be able to build the **whole** wallet from source if he/she likes to.

**Comment by SamouraiDev** [comment]
The source code and build instructions for our flavor of bitcoinj are available here: https://github.com/Samourai-Wallet/bitcoinj  Instructions for any other libs will certainly be pointed to or otherwise provided when we do our own 1.0 version, and that includes our backend API.
