### ISSUE TITLE
ClaimPayNymActivity: buttons not visible on low-res

### ISSUE THREAD

**Issue by anwfr** [Samourai-Wallet/samourai-wallet-android#103]
Buttons from ClaimPayNymActivity are not visible, with low resolution screen (ie Jelly Pro 240x432px).
This prevents using this dialog feature on such devices.
![screenshot_20180125-102023](https://user-images.githubusercontent.com/1021797/35416507-981a4192-0229-11e8-8b4f-0e6353836b97.png)

**Comment by samouraiwallet** [comment]
Thank you Antoine
