### ISSUE TITLE
PayNym not in directory

### ISSUE THREAD

**Issue by s72785** [Samourai-Wallet/samourai-wallet-android#110]
I tried to find my bot in the [directory](https://paynym.is/nyms), but it did not show up.
Maybe there is a connection to it resulting from a payment code I already added before the feature was renamed.
Any chance to publish an existing bot or repeat in case publication failed for whatever reason? Can I e.g. simply reset the wallet; will the payment code be restored and the same PayNym will be generated as well?
The opposite might be true as well and some people maybe want to depublish later.

*edit: @SamouraiDev no choice any more, it was claimed and should have been published to directory. The bot shows up on https://paynym.is/+botname (thx @samouraiwallet ) – not sure if it should show in the "public list" (/nyms) as well or not.

**Comment by SamouraiDev** [comment]
You will be given the choice of claiming your PayNym when you launch the latest version of Samourai Wallet. Then your PayNym will appear in the directory.

**Comment by samouraiwallet** [comment]
> will the payment code be restored and the same PayNym will be generated as well?

Yes, the same wallet will generate the same PayNym Name and Bot image every time after a restore. If you go to the PayNym screen and press the Account icon in the toolbar your Bot's name will be listed above your payment code QR code. You can then navigate to paynym.is/+botname to view your personalized page.

**Comment by vv01f** [comment]
aye, that was clarified by my edit on the description. but nice to hear I am not the only person having a different expectation of a “directory”.
