### ISSUE TITLE
Block explorers

### ISSUE THREAD

**Issue by jorijnsmit** [Samourai-Wallet/samourai-wallet-android#112]
Can I ask why Blockchain.info is not offered? Or my personal preference TradeBlock?

Also UASF Explorer gives me a 502 bad gateway...

**Comment by jorijnsmit** [comment]
Scratch that my new favourite is [Blockonomics](https://www.blockonomics.co/)! With [full SegWit support](https://blog.blockonomics.co/a-segwit-blockexplorer-47cd516dd8c5) and Bech32 adoption.

**Comment by SamouraiDev** [comment]
Block explorer selection will soon evolve to an in-house solution.
