### ISSUE TITLE
Feature request: show all generated (but unused) receive addresses

### ISSUE THREAD

**Issue by LifeIsPizza** [Samourai-Wallet/samourai-wallet-android#113]
Samourai can generate multiple addresses in the Receive activity (up to a maximum set by BIP standards), but if the user reaches the "last" address generated by the wallet without effectively using those before it, the Receive activity doesn't refresh or cycle through the unused addresses already generated.

I'd be interested in a feature to see all the addresses that have been generated but not used.

**Comment by samouraiwallet** [comment]
The app will reset the unused address index once you exit the app and re-enter it. 

So if you are on Address 10, and generate another 10 addresses that remain unused, once you exit and reenter the wallet Address 11 should be displayed. 

Let us know if you aren't seeing this behaviour. 

Thanks!

**Comment by LifeIsPizza** [comment]
I'm not sure if I'm seeing exactly Address 11 in my case (I haven't kept track of the ones I generated and refreshed) but what I'm sure about is that (let's say I'm seeing Address 11 as intended) I see ONLY Address 11, without the ability to cycle through Address 12 to 20 that I've already generated (but not used). Exiting and re-entering the app doesn't "fix" this, hence my original question to be able to cycle through the unused addresses.

**Comment by SamouraiDev** [comment]
You can now generate and display all addresses from Settings->Troubleshooting and selecting the appropriate address calculator. Thank you.
