### ISSUE TITLE
UASF Explorer returns bad gateway when trying to view transaction from the homescreen. 

### ISSUE THREAD

**Issue by Bluethf** [Samourai-Wallet/samourai-wallet-android#120]
uasf-explorer.satoshiportal.com displays bad gateway. 
[https://uasf-explorer.satoshiportal.com/tx/a6084f44e5f6370b2e8b2d93871c9b99b784e5034e4519b07939493f3c729c14]

Maybe use oxt.me for displaying transactions? 
Also, as you guys have acquired oxt, it displayed bech32 address[bc1qqcscmnttr7wpjq8p9m3jqjnk5xr7dq3x2jy6q0] as OP_FALSE 14 06218dcd6b1f9c1900e12ee3204a76a187e68226

**Comment by samouraiwallet** [comment]
Thanks for the heads up.

Once OXT is mobile friendly it will be used to display TXs. It is also being updated to support native segwit (bech32) addresses as we speak. 

SW
