### ISSUE TITLE
Feature request: fractional fees

### ISSUE THREAD

**Issue by dl3br** [Samourai-Wallet/samourai-wallet-android#125]
since txs are large > 100 virtual bytes,  we can subdivide satoshi before multiplying by the virtual size. 

if one look carefully at the mempool, the largest accumulation of txs are at exactly at positive integers positions. for example, paying 5.01 sat / vB, instead of 5.0 sat / vB, one can jump in front of a large number of transactions that all are at exactly 5.0 sat / vB

**Comment by SamouraiDev** [comment]
Have thought about it already as an incremental improvement. Excellent suggestion. You up for a PR or should we handle it?

**Comment by SamouraiDev** [comment]
Done. Custom fees will handle fractional amounts in the next update.

**Comment by dlebrecht** [comment]
better u guys handle it. 

btw, we are working on a powerful real time fee estimator that we will release shortly. 
a rest endpoint can be found here (temporary) 

http://159.100.247.219:3000/btc/deals

and our ui http://159.100.247.219

it would be amazing to see it integrated in a powerful wallet like samurai

**Comment by SamouraiDev** [comment]
Thanks for the tip. We will look into it. Please keep us up-to-date as you approach release.

**Comment by dlebrecht** [comment]
awesome, thanks for the fast reaction! that will be very useful! cheers

**Comment by notf0und** [comment]
Now that the mempool it's mostly empty, that feature can be useful to pay less than 1 sat/byte

**Comment by dlebrecht** [comment]
bitcoind nodes by default don't relay txs paying less than 1 sat/vB

**Comment by halfik** [comment]
Nice. Just came here to report this issue :)

**Comment by KibbledJiveElkZoo** [comment]
. . . just coming in late to add my voice to the crowd that likes the idea of being able to add non-integer satoshi per byte fee rates.  #thumsuptothatshit

**Comment by SamouraiDev** [comment]
This feature is included in the version currently available in Play.

**Comment by dlebrecht** [comment]
@SamouraiDev 
we're releasing the fee estimator

https://fees.truelevel.io

we share websocket and rest endpoints

rest:
http://fees.truelevel.io/api/v1/btc/deals
