### ISSUE TITLE
Fix minor translations in Spanish

### ISSUE THREAD

**Issue by eMaringolo** [Samourai-Wallet/samourai-wallet-android#127]
The last release included a Spanish translation built from scratch. It is way better than the previous before, but it has some issues in the way they affect the layout, word gender mismatches and other minor things.

- [x] "Recibida x.xx BTC" should be "Recibido"
- [ ] In the Sent activity the "Amount" label is unstranslated
- [ ] In the Sent activity the label for the "Custom fee" takes 50% of space and causes the other preset fees to word-wrap because of improper layout.
- [ ] "Support" main menu item is unstranslated
- [x] Hex transaction sending menu label is too long for Spanish.

**Comment by SamouraiDev** [comment]
These PR have been merged for the next update.
