### ISSUE TITLE
wallet doesnt show sent transaction

### ISSUE THREAD

**Issue by vv01f** [Samourai-Wallet/samourai-wallet-android#129]
the recently sent transaction doesnt show up as "in progress" immediately after being being transmitted any more. Only after a while and several "refresh"-pulldown guestures the tx shows up in the list with the expected clock-symbol.

This is irritating users quite a bit. example tx was: d0caaa1688883241b59de4dfb812343f6ca2960113b86cb51060f0cd4da77d0c

**Comment by SamouraiDev** [comment]
Please address all support comments & queries to support@samouraiwallet.com  Thank you.
