### ISSUE TITLE
Design Suggestion: Max. available:

### ISSUE THREAD

**Issue by allinfinite** [Samourai-Wallet/samourai-wallet-android#135]
I find that I tap the send max link regularly without noticing. I think underlining the 'Max. available:' link might help a lot or make it a button. Thanks!!

**Comment by SamouraiDev** [comment]
The 'send' screen has a new design which will be implemented as soon as time and resources allow. Shouldn't be too long from now.

**Comment by sesam** [comment]
Someone wrote (slightly paraphrased) this in a non English chat:

> Yesterday I managed to send my entire balance to my daughter. I would give her BTC worth 100 SEK but the Samurai wallet is a bit tricky. I usually control apps with my left hand. Once you have decided how to pay, you want to scroll the screen and verify everything. I find that chances are high that you can hit the maximum amount of clicks that change the value of the transaction money that the screen is scrolled. It is very possible that I received a confirmation screen that I ignored. I have reproduced the operation and I think it's a mistake that can happen too easily.
> Be careful guys.

I hope this left handed user's experience can be of use in your UI design process. Thank you for your attention.

**Comment by SamouraiDev** [comment]
A new send screen is in active development and will be included in an upcoming release.
