### ISSUE TITLE
Feature request: Full node use beyond broadcast

### ISSUE THREAD

**Issue by gaillard** [Samourai-Wallet/samourai-wallet-android#138]
The full node feature is fantastic! But to get to nirvana if the wallet could use the configured full node (ypub lookup etc) and not talk to any other remote server, we would have a fully decentralized mobile option that is not available anywhere else as far as I know. Thanks!

Also would you mind answering why the current RPC is needed if it is only being used to broadcast?

**Comment by samouraiwallet** [comment]
That is the plan @gaillard - PushTX is just the start of what you can do with Trusted Node. Upcoming updates will allow you to run your own node + local samourai server that talks to your wallet.
