### ISSUE TITLE
ipv6 trusted node crashes the app

### ISSUE THREAD

**Issue by ChrisEbner** [Samourai-Wallet/samourai-wallet-android#142]
Hey there, 

wanted to report a bug with the wallet where I can reliably kill the wallet when entering an IPv6 trusted node. Upon entering ok it will crash the app.

Running Android 7.0

Kind regards, 
Christian

**Comment by samouraiwallet** [comment]
Hi thank you for the report. We will look into this.

**Comment by Crazyk031** [comment]
Trusted node had been removed from the wallet, Dojo is now the required back end.
