### ISSUE TITLE
Feature Request - Use Non-Seed private keys

### ISSUE THREAD

**Issue by stevem0** [Samourai-Wallet/samourai-wallet-android#144]
I would to see an option to keep my private keys without the Seed Phrase.  

Include a option to import private keys for specific addresses.  (and not sweep balance).  Maybe include an Advanced option when importing/sweeping private keys, to just import and not sweep.

Just add some warning like "IF you use private keys independent of Seed Words, your addresses/coins will not be able to be recovered using Seed words"

I like my Samourai Wallet Way Way Way better than all the rest.  The blockchain.info wallet lets you do this.  (You have a list of addresses that can and can not be recovered)

**Comment by zmpetro** [comment]
Samourai should handle this the same way Electrum does. Force the user to create a new wallet if they want to import their own private keys. That way the user doesn't forget that the funds won't be recovered with the seed phrase. However, for this to happen Samourai must support multiple wallets first.

**Comment by vv01f** [comment]
another argument: sweeping reduces privacy as it connects different addresses publicly. so the simplest privacy preserving way would be to import privkeys and use them when needed.

con: backup and keymanagement gets more complex…

**Comment by SamouraiDev** [comment]
We will not be importing private keys beyond sweeping. Thank you.
