### ISSUE TITLE
[UI] 9+ digit PIN accepted when creating new wallet

### ISSUE THREAD

**Issue by RussHarben** [Samourai-Wallet/samourai-wallet-android#154]
When creating a new wallet or importing an external wallet seed, a 9+ digit PIN is accepted (even though the user is prompted to enter a 5-8 digit PIN). 

Once the wallet is created, the PIN entry screen will only accept up to 8 digits and will not allow entry of the  9+ digit PIN.

A workaround is to delete the app and restore the wallet seed / passphrase, creating a new PIN in the process.

**Comment by SamouraiDev** [comment]
Will have a look, asap. Thank you.

**Comment by SamouraiDev** [comment]
Fixed in v0.98.54.
