### ISSUE TITLE
Using a Full node requires exposing RPC port to the wallet.

### ISSUE THREAD

**Issue by tyzbit** [Samourai-Wallet/samourai-wallet-android#155]
## The Issue
As I understand it, if I am to use a full node with Samourai, I must also give Samourai **full control** over my node via the RPC commands.  This means the wallet can:

* ban peers
* shut down the node
* adjust runtime parameters

This is too much access to give what should functionally just be a relay and block explorer.  Also, if I am to use my own full node while travelling, I need to be able to access it which means naiive users might expose their full nodes (and their RPC ports) to the Internet, or users must set up complicated VPNs for this functionality.

## How to fix the Issue
Allow users to specify their own full node and communicate to that node on the standard Bitcoin port(s).  This will protect users' security and privacy.

**Comment by Crazyk031** [comment]
Issue no longer relevent as trusted node has been removed & Dojo is the required backend now
