### ISSUE TITLE
Feature Request: Preview a Send Transaction's Meta-Information: 

### ISSUE THREAD

**Issue by KibbledJiveElkZoo** [Samourai-Wallet/samourai-wallet-android#156]
It would be helpful for me to be able to preview the characteristics of a send transaction before sending it — specifically the size in bytes that it will be, so I can fine tune the fee as to align with using an entire unspent transaction output or to sum the send amount and the fee to a certain figure.

The preview that the desktop version of Electrum has is the model I know for this feature.  It includes the information of the transaction size, the fee amount, the fee rate and the inputs and outputs of the transaction.

Over the course of sending many transactions to individuals, exchanges, retailers, my own other wallets . . . I have often used the preview information to help me fine tune what amount I want to send or what fee rate I want to use to have a certain total fee, or to help increase/decrease amounts so that they fit with certain inputs's balances.

**Comment by samouraiwallet** [comment]
This should be addressed in upcoming UI updates.
