### ISSUE TITLE
BIP32 Key derivation path

### ISSUE THREAD

**Issue by jakubtrnka** [Samourai-Wallet/samourai-wallet-android#167]
I'd like to know the exact BIP32 key derivation path that the wallet is using. The xPub, yPub and zPub in settings do not match the extended public keys that are produced in other software (like Electrum). Ideally show the path in small font beneath each address, or et least give that information in wallet summary.

**Comment by SamouraiDev** [comment]
We use the same derivations as used in other wallets such as Mycelium, blockchain.info, Coinomi and more. Our BIP49 derivations work with Trezor and Ledger. Path information will be displayed in an upcoming update.

**Comment by jakubtrnka** [comment]
Oh, now I get it. The setup-passphrase was indeed BIP39 passphrase. That's the reason the addresses were different. I completely forgot I set it up. Now it's clear. thanks.
