### ISSUE TITLE
fee estimation

### ISSUE THREAD

**Issue by dl3br** [Samourai-Wallet/samourai-wallet-android#176]
today the fee estimation was very off (towards the low side), and now is very off (towards the high side). its lagging behind. suggesting past for the present.

i suggest looking into https://github.com/zkao/btc-congestion-manager
 which is served here https://fees.truelevel.io

its been in production for about 3 months, with no downtime. 

the fee estimates are remarkably spot on, and very responsive to mempool changes (<10 seconds delayed). it's a mempool depth detector (how deep is the mempool), and uses past data just to estimate instant velocities for mempool growth (at different depth thresholds). very simple model. high school physics. no fancy statistics.

**Comment by SamouraiDev** [comment]
We work with a 72-hour mempool. We are satisfied with the way fee estimations are working at the moment but the functionality is definitely subject to ongoing development and fine-tuning. Thank you for your suggestion.
