### ISSUE TITLE
iOS Wallet Support？

### ISSUE THREAD

**Issue by AlleniCode** [Samourai-Wallet/samourai-wallet-android#178]
Is there an iOS wallet project?

**Comment by SamouraiDev** [comment]
Yes.

**Comment by AlleniCode** [comment]
Where can I fine the source code？

**Comment by samouraiwallet** [comment]
You will be able to find it here when we release it.

**Comment by AlleniCode** [comment]
iOS wallet Completed？

**Comment by AlleniCode** [comment]
@SamouraiDev @samouraiwallet  Hi，is iOS wallet released？
