### ISSUE TITLE
DeterminsticKey serializePuB58(Networkparms,purpose)

### ISSUE THREAD

**Issue by SephirothLT** [Samourai-Wallet/samourai-wallet-android#179]
![image](https://user-images.githubusercontent.com/20485889/41762605-e17b1618-762d-11e8-8482-d372b28af9da.png)
I found in HD_Account，aKey.serializePuB58(Nteworkparams,int purpose ),
but in original bitcoinj  have not this method,this method is custom by yourself?
This is yours:
![image](https://user-images.githubusercontent.com/20485889/41762691-265bcab6-762e-11e8-8fff-f6a17875dcd8.png)
This is original:
![image](https://user-images.githubusercontent.com/20485889/41762719-380c5ce4-762e-11e8-98ff-0f903f3b4016.png)

**Comment by SamouraiDev** [comment]
https://github.com/Samourai-Wallet/bitcoinj/blob/745b8dca56d1afcf72d8fe5db980b57dee22a2a5/core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java#L504
