### ISSUE TITLE
Rounding error while scanning a payment request

### ISSUE THREAD

**Issue by deafboy** [Samourai-Wallet/samourai-wallet-android#183]
While scanning the following payment request:

    "bitcoin:bc1qma42x722046pqlnevrd7myk9250ckknmpagqad3h2ddexqvw9u5svjrnar?amount=0.00476392"

![screenshot from 2018-07-13 23 50 11](https://user-images.githubusercontent.com/908822/42715519-b3c70328-86f7-11e8-961a-74c59b07bcb6.png)

The amount displayed and sent by Samourai is not correct:

![samourai_rounding](https://user-images.githubusercontent.com/908822/42715674-51821292-86f8-11e8-85cf-aa48ffec8a3a.png)

Same applies for 0.00476391, but not for 0.00476393.

**Comment by SamouraiDev** [comment]
Fix released.
