### ISSUE TITLE
GUI: Max available balance button triggering unintentionally.

### ISSUE THREAD

**Issue by hikedev** [Samourai-Wallet/samourai-wallet-android#190]
I did use the samurai wallet quite frequently for testing my shop system with bitcoin.

One problem I encountered is that if you scan an address successfully and the software is switching to the payment interface, I'm unintentionally hitting with my fingers the max available balance button. One of the reason this is happening is because the android keyboard is appearing and you try to hide it.

It would be nice to change the position to somewhere in the bottom or give a warning if you did hit the button and don't display after scanning an address the keyboard.

**Comment by SamouraiDev** [comment]
A new send screen UI is now in testing. Thank you.

**Comment by hikedev** [comment]
Sir, I have to thank you ;)
