### ISSUE TITLE
Share button for receive address gives "no such file or directory" error

### ISSUE THREAD

**Issue by dammkewl** [Samourai-Wallet/samourai-wallet-android#194]
Reproducibility not checked, but this is basically what I did:

1. Started a fresh new wallet (without claiming a paynym)
2. (Changed some default settings that I don't think should be relevant, ask me if required)
3. Tapped "Receive"
4. Hit the "share" icon in the top right corner
5. Hit "yes" in the popup that asks "Share this receive addres?" (there's more text there but meh)

This happens every time I hit the share button and so I can't make use of the "share address" functionality.

Expected result: my OS asking me how to share the data.
Actual result: An error message at the bottom of the screen saying "No such file or directory".

The app has all the permissions (camera, sms, storage, telephone)

Will PM more private details such as phone model, if required.

**Comment by SamouraiDev** [comment]
This was OS version dependant. Issue cleared up for you?

**Comment by dammkewl** [comment]
Yes, it works now, sorry for the late response.
