### ISSUE TITLE
Feature request: hide bip38 password during typing (change input type to 'password')

### ISSUE THREAD

**Issue by snmot** [Samourai-Wallet/samourai-wallet-android#216]
The problem is, when I'm trying to spend a bip38 encrypted private key the password field is just plain text input (not password). It causes to consequences:

1. Android keyboard application "remembers" what I'm typing and suggests me (or hacker) words from the password next time. 
2. Android keyboard application capitalize the first letter of the first word in the password.
3. Sombody can see the password by chance.

I beleive the password field should have "password" type.

**Comment by SamouraiDev** [comment]
This is addresses in the next update. Thank you.
