### ISSUE TITLE
What means of Ricochet or BOLTZMANN  in SendActivity?

### ISSUE THREAD

**Issue by SephirothLT** [Samourai-Wallet/samourai-wallet-android#219]
Hi,I have some confuse in SendActivity,What means of SendType ==Ricochet or BOLTZMANN?

**Comment by SamouraiDev** [comment]
Ricochet is Ricochet. Boltzmann is the "code name" for STONEWALL spend.

**Comment by SephirothLT** [comment]
Thanks!,But the sendType is  STONEWALL  have some benefit?

**Comment by SamouraiDev** [comment]
Please DYOR.

**Comment by SephirothLT** [comment]
Thanks!
