### ISSUE TITLE
Balance and transactions disappeared

### ISSUE THREAD

**Issue by kristapsk** [Samourai-Wallet/samourai-wallet-android#226]
I set up Samourai Wallet for a friend some weeks ago. Created new wallet, she wrote down BIP39 seed, then sent some BTC to it from Mycelium (I have iPhone, so no Samourai for me yet). BTC appeared on Samourai, transaction confirmed, everything was ok.

But some day or two later friend told me that wallet shows zero balance. I checked and, yes, there was zero balance and no incoming transactions.

I re-created same wallet in Electrum from seed and it also shows zero balance and no transactions. Destination address has BTC there, but address does not appear in Electrum's initial receive address list (some 50 addresses or so).

What could have happened? Samourai choose some wrong HD derivation path initially or some other bug?

I can provide developers with BIP39 seed and destination address of initial transaction in private, if that helps.

**Comment by SamouraiDev** [comment]
Please contact support@samouraiwallet.com Thank you. Great work on your Ricochet (and other) scripts, btw.

**Comment by SephirothLT** [comment]
Have you solve this problem ? I have the same question! @kristapsk

**Comment by kristapsk** [comment]
Yes, solved today! Routing through Tor was enabled in Samourai Wallet's settings, but after phone restart or something Orbot autostart hasn't worked. After manually starting Tor in Orbot, balance and transaction history appeared. At the end decided to turn off routing through Tor for the person, as working wallet with less privacy is better than non-working wallet and bad UX for a Bitcoin newbie.

I guess, Samourai and Electrum uses different BIP39 derivation paths, that's why Electrum also showed zero balance.

**Comment by overcoin** [comment]
Routing through Tor/Orbot is not the reason. This issue is not solved yet. I'm not sure why it was closed.

**Comment by jodobear** [comment]
Issue isn't closed.

I opened a new wallet to try it out for the first time so sent a transaction to my new Samourai wallet. But, the transaction does not appear nor does the balance. I manually turned Tor on, with routing through Tor in the wallet, then turned it off and turned off routing in the wallet as well, refreshed it multiple times, restarted my phone multiple times, but no, i don't see the transaction while it exists on the blockchain!

I even tried to load the wallet in Electrum using the BIP39 seed but even there it doesn't show the transaction and balance! And the documentation and FAQ section on the website is not helpful.

Firstly, why can't i load my Samourai wallet in Electrum or is there another wallet where i can load it, if not why is it designed that way?

Secondly, how do i retrieve my funds? This has been nerve wracking..

**Comment by neilstephens** [comment]
I have the same problem. Seed plus passphrase won't restore in any wallet. To make matters worse, samurai.txt backup won't restore either, and it's not an incorrect passphrase, because it behaves differently when I put in an incorrect one deliberately.

Can we get this issue reopened please?

Was there a time in the past that the BIP39 code had a defect, so the seed phrase is screwed up?

**Comment by SamouraiDev** [comment]
Please refer such issues to support@samouraiwallet.com. This will not be used as a support channel. Thank you.

**Comment by pundoo** [comment]
Encountered same issue. Restored in Mycelium Wallet and it showed the correct balance.

**Comment by HarryBuko** [comment]
Hey, I have the same issue
How did you retrieve it with Mycelium?
Rgds
