### ISSUE TITLE
Few untranslated strings

### ISSUE THREAD

**Issue by un1t** [Samourai-Wallet/samourai-wallet-android#227]
Hi!
Nice wallet. I'm was surprised that it has russian translation. I found few untranslated strings.

At first screen at the bottom, there are message "Encrypted backup detected" (could be translated as "Обнаружена резервная копия") and button "Restore" ("Восстановить").

On the receiving screen there is button "Advanced" and when you click on it there are few other strings:
"Request Amount" - "Сумма к получению"
"Address Type" - "Тип адреса"
"Segwit compatibility" - "Segwit совместимый "
"Path" - "Путь"
"Segwit native" - "Segwit чистый"
"Legacy" - "Устаревший"

**Comment by un1t** [comment]
Seems this things are absent in **app/src/main/res/values/strings.xml**
For example string "Encrypted backup detected" is found in **app/src/main/res/layout/activity_landing.xml**

Here is a code:
```
 <TextView
            android:layout_width="274dp"
            android:padding="14dp"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            android:gravity="center_vertical"
            android:text="Encrypted backup detected" />
```
So to do translation at first you need to extract such strings and put them in **strings.xml**

**Comment by engenegr** [comment]
@un1t true, It could happen because of absent lines in strings.xml, the only file we actually translated. So thank you, because it is hard to me now to follow Samourai development.

**Comment by SamouraiDev** [comment]
Please include any translations and corresponding code changes in a pull request and I will have a look. Thank you.
