### ISSUE TITLE
Feature request: SPV broadcast

### ISSUE THREAD

**Issue by s-tikhomirov** [Samourai-Wallet/samourai-wallet-android#232]
As [the website states](https://samouraiwallet.com/features/trustednode), "Samourai uses our own Iceland based bitcoin nodes to push transactions to the bitcoin network" (if the trusted node is not specified). Isn't it the central point of failure which provides a technical possibility to log all transactions passing through the servers? Why not use a regular DNS-based bootstrapping and broadcasting to a set of random nodes?

P.S. Why also reveal the geographic location of your server? Considering that there are [only 5 nodes in Iceland](https://bitnodes.earn.com/nodes/?q=Iceland) and only 1 of them advertising a full set of services...

**Comment by SamouraiDev** [comment]
Trusted Node (to be used securely) is available to mitigate any issue you might have. Aside from that, Trusted Node functionality is being reinforced short term. Thank you.

**Comment by s-tikhomirov** [comment]
You are free to close the issue, but the reply is not clear. "Trusted node" implies that I run my own full node which accepts incoming connections. For the vast majority of users this is not the case. If I understand correctly, by default Samourai broadcasts transactions through a centralized node maintained by its developers. Why not provide the users with the option to use a set of random nodes from the network, as full nodes do?

And what does "reinforced" mean in this context?
