### ISSUE TITLE
GUI: fix sat/b fee buttons, some drop-down texts are too long

### ISSUE THREAD

**Issue by nvyo** [Samourai-Wallet/samourai-wallet-android#243]
The square "sat/b" fee buttons in the "Send" screen don't envelop the Russian text properly in the latest release (Russian "сат/б" text gets a line break after "/" and the last character is on the new line and not seen in full). They are also impractical in a sense that they don't allow for more than 5 characters for the units of measurment, while ideally it would be better to have 8 for Russian translation specifically. For what it's worth, I find the buttons' positioning and shape unoptimal altogether. Maybe it's better to make them rectangular and arrange vertically? Or maybe take the "sat/b" out of the button texts since it repeats three times anyway.

As to the texts in the drop-down menus, some of them become too long when translated. For instance, "Activate all archived payment codes" and "Sync all payment codes" entries in the drop-down menu don't fit into their respective areas when translated into Russian, ending with ellipsis and causing possible confusion as to what the entry actually does. I would suggest giving these particular actions full-fledged GUI buttons, possibly under "Payment codes actions" title so as to shorten the text inside the buttons. Please also allow for some extra space in all crucial interface entries, because English tends to be the shortest language: texts in other languages take up more space. For instanse, Russian text is on average 1.3—1.5 times longer than its English counterpart; sometimes fitting it into fixed-sized buttons or text fields requires a great deal of creativity.

**Comment by SamouraiDev** [comment]
The whole spend UI has been retooled. Will be rolled out soon. Thank you.
