### ISSUE TITLE
Support bustapay

### ISSUE THREAD

**Issue by RHavar** [Samourai-Wallet/samourai-wallet-android#247]
As I know samourai tries to be the most privacy friendly wallet, it would be great if it was the first mainstream wallet to implement sending bustapay payment.

Here's the spec: https://github.com/RHavar/bips/blob/master/bip-bustapay.mediawiki

It's actually a pretty straight forward protocol, that's a bit easier to develop than it looks -- and offers pretty powerful privacy improvements.

I have somewhat of a reference implementation here, which is pretty easy to follow along:
https://github.com/RHavar/bustapay/blob/master/send/send.go#L16

And to save anyone the trouble of setting up a bustapay receive server, I have one already running on testnet:  http://test.bustapay.com 

e.g. with the reference client you can go:

```
bustapay send $(curl http://test.bustapay.com/get-newish-address) http://test.bustapay.com  0.01
```

which would make a  0.01 BTC bustapayment to a (new) address on that server.   I'd also love any feedback before that spec is fully finalized.

I've also got some buy-in by some bitcoin businesses who will support it production -- so of all the privacy proposals, I really think this one has the biggest shot of moving the needle.

**Comment by SamouraiDev** [comment]
We have similar private payment schemes in development. Thank you.
