### ISSUE TITLE
Why create two account？

### ISSUE THREAD

**Issue by mivanzhang** [Samourai-Wallet/samourai-wallet-android#250]
Question one:
the code in [HD_Wallet](https://github.com/Samourai-Wallet/samourai-wallet-android/blob/develop/app/src/main/java/com/samourai/wallet/hd/HD_Wallet.java) constructor create two HD_Account ?

Question two:
actually  create three wallet: Base wallet、bip49 wallet and bip84 wallet ,Why？

**Comment by SamouraiDev** [comment]
Please direct support issues to support@samouraiwallet.com Any service/product related questions can be addresses on our Telegram group: t.me/SamouraiWallet Thank you.

**Comment by mivanzhang** [comment]
I think this is a technical problem ,but you always ask me to send email to  support@samouraiwallet.com ,you made me crazy
