### ISSUE TITLE
The [Send] button won't show

### ISSUE THREAD

**Issue by qertoip** [Samourai-Wallet/samourai-wallet-android#252]
On the send screen the green [Send] button that was supposed to be at the bottom simply won't show anymore. It's a GUI glitch. Sometimes by a sheer luck the button does show up. It doesn't matter whether the inputs are filled up or not. Most recent Samourai 0.98.91 @ most recent Android.

**Comment by SamouraiDev** [comment]
Please contact support@samouraiwallet.com Thank you.

**Comment by qertoip** [comment]
No, this is to report an actual bug.

The button sometimes won't show up **even though the input fields are filled correctly** meaning the amount below max and the correct recipient address.

The root cause might be doing networking in the UI thread.

Using with Tor seems to amplify the issue although it is reproducible w/o Tor as well.
