### ISSUE TITLE
UI randomly pauses (freezes) for seconds

### ISSUE THREAD

**Issue by qertoip** [Samourai-Wallet/samourai-wallet-android#254]
The user interface randomly freezes for seconds. This is most evident on the main view with a list of transactions and (+) button. But it happens on other views as well. Most of the time the UI unfreezes after a few seconds and user can continue using the wallet until the next glitch. While never a show stopper this is super annoying.

Possible root cause is performing IO / networking / heavy logic in the UI thread.

Tested on Google Pixel 2, most recent Android (stock / not rooted), and most recent Samourai Wallet at the date of ticket creation.

**Comment by SamouraiDev** [comment]
UI overall is ongoing and a larger refactor is scheduled to begin shortly.
