### ISSUE TITLE
To improve UX the send screen should always show the [Send] button

### ISSUE THREAD

**Issue by qertoip** [Samourai-Wallet/samourai-wallet-android#255]
This is a separate thing to my recent bug report #252.

On the send screen the green [Send] button only appears if all inputs are filled correctly. This really gets user lost. Simply showing inactive button instead of no-button would already help to some extent, and is an easy fix.

Ideally though the [Send] button should be always active and report feedback on incorrect input data when clicked. Obviously, this UX improvement requires some more involved development.

**Comment by SamouraiDev** [comment]
The Send UI has been completely redesigned and will be released shortly.
