### ISSUE TITLE
For RBF transactions [INCREASE TX FEE] button does nothing

### ISSUE THREAD

**Issue by qertoip** [Samourai-Wallet/samourai-wallet-android#256]
Context: I have enabled "Spend using RBF" in Settings and then created a transaction. Transaction is propagated in the network and visible in the block explorers. The transaction **is** correctly reported as RBF by bclock explorers (Blocktrail). The transaction has 0 confirmations after 2 hours. I decide to bump the fee.

However, clicking [INCREASE TX FEE] option does exactly nothing (no message, no error, just come back to transactions list, the fee does not get bumped, the tx id does not change either).

Trying multiple times with the button, restarting Samourai Wallet, toggling on/off Tor - did not help.

**Comment by bitschmidty** [comment]
@SamouraiDev I have run into this issue as well. I had assumed it was related to either not having a change address, or not having sufficient change to perform the transaction fee increase per BIP125. But perhaps there is another bug happening.

![rbf-samourai-fail-bump 1](https://user-images.githubusercontent.com/1615772/51923399-7c694200-23b0-11e9-83ea-508343c09f6a.png)
