### ISSUE TITLE
server api unspend utxo 

### ISSUE THREAD

**Issue by mivanzhang** [Samourai-Wallet/samourai-wallet-android#260]
because we cannot access your sever api ,so we intend to use blockchain api instead, but I found a problem ,when I invoken following api:

https://api.samouraiwallet.com/test/v2/unspent?active=tpubDC8xsLLA9k3ACfCLm9WWwm8aDXqgf79ec2hGQprVcoPnv37PbdzbXcUcfLuWkQcEoziNexPnhHE6652o45m8EXWV7JXY1CdWFqgE9Gj2AH4%7CtpubDC8xsLLA9k3AFovAzZ9KJjWGMV8RDPcegk5zSuLf5nb7ChujGV71c71UoqTb1TR2HBWc8m3wc1AHvgaZoAMGwZeziFU4xruR2TPEh9UV8uo%7CtpubDCDzB47M67om4kDPw6Gw5hWnRK8KLxssPDA1hW7bh2qYG61y9UHoj9JnDTsvM6QmLWvmqu9Fk23Jo19Jot68Qcc35rTenE6PV49L5b7Fe6a%7CtpubDDtX94YHr4PWtAx5uZgQdU7wWmzmgXWDocBaZZXVRJHRFFqVBHSPCf1bCFxY4opdczRRg4hr3t1ZXf3FycSNd8qpX8XeaxejrEN4jwkSHLJ

it return unpsend utxo

but when I invoke 
https://testnet.blockchain.info/unspent?active=tpubDC8xsLLA9k3ACfCLm9WWwm8aDXqgf79ec2hGQprVcoPnv37PbdzbXcUcfLuWkQcEoziNexPnhHE6652o45m8EXWV7JXY1CdWFqgE9Gj2AH4%7CtpubDC8xsLLA9k3AFovAzZ9KJjWGMV8RDPcegk5zSuLf5nb7ChujGV71c71UoqTb1TR2HBWc8m3wc1AHvgaZoAMGwZeziFU4xruR2TPEh9UV8uo%7CtpubDCDzB47M67om4kDPw6Gw5hWnRK8KLxssPDA1hW7bh2qYG61y9UHoj9JnDTsvM6QmLWvmqu9Fk23Jo19Jot68Qcc35rTenE6PV49L5b7Fe6a%7CtpubDDtX94YHr4PWtAx5uZgQdU7wWmzmgXWDocBaZZXVRJHRFFqVBHSPCf1bCFxY4opdczRRg4hr3t1ZXf3FycSNd8qpX8XeaxejrEN4jwkSHLJ

 I got null !!

What's the difference between your server api and blockchain? or Does your server api done something else.

**Comment by SamouraiDev** [comment]
Ask blockchain.info, pls.

**Comment by mivanzhang** [comment]
Thank you anyway
