### ISSUE TITLE
My samourai wallet keeps crashing when trying to send

### ISSUE THREAD

**Issue by Mikadily** [Samourai-Wallet/samourai-wallet-android#262]
The problem began when my utxos increased up to 40 at the moment (bunch of P2PKH, bech32, P2SH addresses), occasionally I try to send a specific amount and when the screen shows "Broadcasting transaction" the app crashes. The only way to get out of the loop is to try to send different amount to different address. I have a feeling that is something to do with STONEWALL (as it wasn't a problem with little utxos). Is there a way I can help debug this?

**Comment by SamouraiDev** [comment]
Contact us on support@samouraiwallet.com so we can have a look.
