### ISSUE TITLE
transaction no output 

### ISSUE THREAD

**Issue by mivanzhang** [Samourai-Wallet/samourai-wallet-android#263]
I use the wallet to send a transaction in the testNet
tx hash:7413b5f7cba8cd2dabe2ccb29c17452213e339bb095103297e2c164ea2511f04
 Then I get null output:
api is here
https://api.samouraiwallet.com/test/v2/multiaddr?active=tpubDC8xsLLA9k3ACfCLm9WWwm8aDXqgf79ec2hGQprVcoPnv37PbdzbXcUcfLuWkQcEoziNexPnhHE6652o45m8EXWV7JXY1CdWFqgE9Gj2AH4

**Comment by SamouraiDev** [comment]
I kindly request that you direct any support issues to support@samouraiwallet.com  Thank you.
