### ISSUE TITLE
Gradle failed

### ISSUE THREAD

**Issue by mayanhu** [Samourai-Wallet/samourai-wallet-android#271]
Could not resolve com.samouraiwallet:whirlpool-client:0.0.1-SNAPSHOT.

**Comment by michaelWuensch** [comment]
You can resolve the issue yourself by installing Whirlpool-protocol and Whirlpool-client locally.
1. Install maven
2. clone Whirpool-protocol and Whirlpool-client from github
3. install Whirpool-protocol with the following command:  mvn clean install
4. install Whirpool-client with the following command: mvn clean install -Dmaven.test.skip=true
5. build Samourai Wallet with gradle
