### ISSUE TITLE
Feature Request: Support for full nodes using tor (.onion address)

### ISSUE THREAD

**Issue by kn0wmad** [Samourai-Wallet/samourai-wallet-android#276]
I don't know how difficult it would be, but I would love to see support for trusted nodes that are on .onion (as opposed to IPv4/6) addresses.
Thank you for all your hard work, Samourai is a great wallet!

**Comment by SamouraiDev** [comment]
Our Dojo full node will be running a Tor hidden service and only be accessible via .onion address.

**Comment by pardus79** [comment]
I'd like to second this feature request.

It's great that the node on Dojo is on tor, but for those of us who don't run Dojo we would like to be able to connect to our own full nodes over tor (bonus if we can make it work w/ hidden service client keys).
