### ISSUE TITLE
UTXO's Not Recognized

### ISSUE THREAD

**Issue by jamespedwards42** [Samourai-Wallet/samourai-wallet-android#278]
I have received 2 transactions to my first two Bech32 addresses from a wallet created and using the latest version of Samourai Wallet.  I received a notification from the app that the expected balance was received.  However, in the app the balance remains at 0 and does not present any transactions.  Also, when I try to send it says the balance is 0.

I added the pub keys to Sentinel and the two transactions show up with the correct/expected balance.

**Comment by jamespedwards42** [comment]
Just tested a P2SH address and still have the same problem.  Anyone tested Samourai on a Pixel 3?

**Comment by SamouraiDev** [comment]
Please contact support@samouraiwallet.com. Thank you.
