### ISSUE TITLE
Feature Request: Show amounts in alternative currency

### ISSUE THREAD

**Issue by pabo3000** [Samourai-Wallet/samourai-wallet-android#282]
In the preferences should be an item alternative currency. It contains three subitems:

1. Switch on/off: alt. currency
2. Choose service to obtain conversion rate
3. Choose alternative currency f. e. €, ¥ or $

Next to amounts you can see the converted amounts. F. e. 0,34 BTC (657 €). You can choose to enter amounts in alternative currency for send and receive. You can toogle the currency by touching the currency symbol.

**Comment by SamouraiDev** [comment]
Samourai Wallet will no longer be displaying fiat exchange rates.
