### ISSUE TITLE
"A STONEWALL spend could not be ..." Warning

### ISSUE THREAD

**Issue by LouisWayne** [Samourai-Wallet/samourai-wallet-android#286]
When I try to send some BTC with Ricochet enabled and 1 sat/b as fee, it shows an warning message:
`A STONEWALL spend could not be composed with your current set of unspents. If you require a STONEWALL spend tap 'NO' and try again with a modified set of unspents`.  I have no idea what this means.  Why can't Samourai wallet just find the proper amount to enable STONEWALL?  And how can I enable STONEWALL feature in this case?

**Comment by RockyRococo** [comment]
Not all transactions will meet the requirements/conditions for STONEWALL to activate. The message you're seeing is notifying you that the transaction you are attempting to send can't be sent as a STONEWALL spend. You can still send that transaction without STONEWALL.

**Comment by SamouraiDev** [comment]
See the algo here: https://gist.github.com/SamouraiDev/4ced85a29996dd56781e2bf319b93aaf
