### ISSUE TITLE
PayNym transactions cannot be seen after restroring wallet

### ISSUE THREAD

**Issue by bodorb11** [Samourai-Wallet/samourai-wallet-android#295]
After I restored my wallet, the PayNym transactions were not loaded. On the other hand, for some weird reason, the wallet saw my earlier PayNym contacts, but I still had to repeat the initial PayNym transactions. After having done so, I was able to see all my PayNym transactions. I guess this is still unexpected behaviour.

**Comment by SamouraiDev** [comment]
Please refer all support issues to support@samouraiwallet.com. Thank you.
