### ISSUE TITLE
Transaction disappeared

### ISSUE THREAD

**Issue by LouisWayne** [Samourai-Wallet/samourai-wallet-android#298]
I am using the version 0.98.95, and my Android version is 5.0.1.

When I turned on my Android phone, the wallet doesn't show all the transaction history and my balance.

I restarted my phone but still no luck.  How can I fix the issue?

**Comment by LouisWayne** [comment]
Nevermind, I just updated the app, and it works fine now

**Comment by SamouraiDev** [comment]
Thank you for the update. In the future, please refer all support issues to support@samouraiwallet.com.
