### ISSUE TITLE
[Feature Request] Device Storage Encryption

### ISSUE THREAD

**Issue by ajvsol** [Samourai-Wallet/samourai-wallet-android#299]
[Also deployed](https://listed.standardnotes.org/@sn/824/enhanced-security-with-device-storage-encryption) in other open-source apps like Standard Notes, this ensures unencrypted data about your wallet is never accessible on your device without first decrypting it.

**Comment by InvertedX** [comment]
we already have an encryption 
https://github.com/Samourai-Wallet/samourai-wallet-android/blob/develop/Samourai-Wallet-features.md#security
