### ISSUE TITLE
Unit choice not saved on reopening wallet.

### ISSUE THREAD

**Issue by ravcodebase** [Samourai-Wallet/samourai-wallet-android#307]
Issue - When choosing "sat" as the displayed unit, the choice is not retained when the wallet is closed. Opening the wallet defaults back to "BTC" units.
Solution - retain the user desired unit choice, when the wallet is opened it default to the previous unit choice of the user.

**Comment by ravcodebase** [comment]
Option to have a setting for unit choice in the "settings" -> "wallet" menu.

**Comment by Crazyk031** [comment]
@miguelmartinn9 added this functinality to the wallet & his PR was merged to bring a saved state when selecting between sat/btc
