### ISSUE TITLE
Use of standard Android keyboard potentially exposes mnemonics

### ISSUE THREAD

**Issue by patriceac** [Samourai-Wallet/samourai-wallet-android#310]
While restoring my wallet on Android, I noticed that after entering the same mnemonics a couple time over several restorations, the keyboard would start suggesting the next mnemonic before I even started typing it. E.g. as I type “excess”, the next suggested word would be “owner” along with a couple other seemingly random words which actually happen to all be part of my passphrase. Pretty disturbing to say the least. FWIW, I think a virtual keyboard would be *much* safer.

**Comment by InvertedX** [comment]
fixed 9487d0cdbbac9db259bd57be44a0eaba1990a60a
