### ISSUE TITLE
No ability to just type a Paynym?

### ISSUE THREAD

**Issue by Transisto** [Samourai-Wallet/samourai-wallet-android#311]
I thought the benefit of PayNyms was to make it easy to transmit.

Someone sent me his PayNyms and I had to copy paste stuff back and forth to paynyms website to get the raw payment code.

**Comment by SamouraiDev** [comment]
Go to PayNyms->New Contact->Paste

**Comment by Transisto** [comment]
Then I have to copy paste the long payment code, Can't just write the PayNym there.

Doesn't that defeat the purpose of the short name whole concept?
