### ISSUE TITLE
Address reuse when sending to a PayNym.

### ISSUE THREAD

**Issue by Transisto** [Samourai-Wallet/samourai-wallet-android#313]
I send two transaction weeks apart to a paynym both get sent to the same address.

According to BIP47 it should be possible to send to other receiving addresses.

![image](https://user-images.githubusercontent.com/388716/55262910-cc944180-5245-11e9-9086-c9b33de27ac7.png)

**Comment by SamouraiDev** [comment]
Which version of Samourai are you using?

**Comment by Transisto** [comment]
I update whenever I can

**Comment by SamouraiDev** [comment]
Might be that the payload was not updated and therefore the didn't keep track of the previous index used into that channel. If you can make sure that the channel is re-synced on both ends it should not happen again.

**Comment by Transisto** [comment]
The other party had not completed all steps, Seems to be working now.

Pretty sure I could see, Ready to receive / Ready To send on my end.

Thank you.

**Comment by Transisto** [comment]
5 transaction all sent to same address. I was mistaken, all steps have been done on both side and it still doesn't work.

**Comment by SamouraiDev** [comment]
Make sure that you exit the app using the back key. This will save the state of the payment tunnel. This should be done on both ends. Make sure that both sides of the tunnel are in sync. A long press on a PayNym entry will display the ingoing and outgoing indexes for that PayNym.
