### ISSUE TITLE
Urgent fee too low.

### ISSUE THREAD

**Issue by Transisto** [Samourai-Wallet/samourai-wallet-android#316]
I get suggested a fee of 1.5sat/B at max while mempool has been averaging 6sat/byte over last 24h and was much worst before that.

**Comment by SamouraiDev** [comment]
Our fee estimates are very accurate but are subject to rapid changes in fee market conditions, as are occurring frequently at the moment. Check on mempool conditions and use the fee slider to better ajust the fee rate used for your transaction.

**Comment by Transisto** [comment]
Dude, the URGENT FEE was 1.5sat, There was no way to increase it beyond that.
