### ISSUE TITLE
Restore from mnemonic fails consistently

### ISSUE THREAD

**Issue by dscotese** [Samourai-Wallet/samourai-wallet-android#32]
The feature I really wanted allows me to use my own personal very long passphrase as the master seed for an HD wallet.  I think that is the "restore from mnemonic/seed" feature, but it doesn't work for me.

If this feature worked properly, the wallet could be erased or reset or whatever.  Maybe it gets erased after the app isn't used for a while.  So when authorities demand to see it, you can show that it's installed, but there's nothing there, or with a small additional feature (described below), you could enter your password and show that your BTC wallet is empty.

Steps to produce:
1. Install Samourai wallet.
1. Open Samourai wallet.
1. Choose to restore wallet.
1. Choose mnemonic/seed.
1. Enter any mnemonic you want.
1. Create your PIN code.
1. Verify your PIN code.
1. Wait for it...
1. Read the error, "error restoring wallet."

It may be the case that Samourai decided not to support mnemonics that don't have built-in error checking, so I thought of a solution to that problem.  When you use a random mnemonic to create a new wallet, a checksum can be created afterwards, and translated into a two-word BIP-39 "easily remembered fingerprint."  Then give that to the user.  Now you can verify that the mnemonic was entered correctly, either by asking for the two words, or presenting a bunch of words and asking the user to select them.  Obviously, if the user indicates that they are creating a new wallet, you just provide them to be memorized.

My favorite version of this feature: After creating a wallet from a mnemonic, you tell the wallet how many keystrokes from the end of the mnemonic you want to use as the password and how long to keep the HD wallet open after entering the password.  If you enter the wrong password, it creates a new wallet using that new mnemonic.  This allows the user to have any number of wallets, each identified by a password.  Once a wallet is open, the user can navigate to a screen that displays the two BIP-39 checksum words so they can verify that they entered the mnemonic correctly.

**Comment by SamouraiDev** [comment]
You are correct in assuming that Samourai does not support mnemonics without a correct checksum. This is standard BIP39/BIP44 and we do not have any intention of changing that. I'm assuming that is why wallet restore consistently fails for you.

We will be providing a revised-UI around BIP39/BIP44 shortly but the underlying code based on those 2 BIPs will remain unchanged.
