### ISSUE TITLE
Send via paynym, shows 0.0 BTC available balance.

### ISSUE THREAD

**Issue by Transisto** [Samourai-Wallet/samourai-wallet-android#322]
To reproduce : 
Tap +
Tap PayNyms
Select a PayNym
"Send through this payment channel?" tap "YES"

then it shows the app logo, as if it's opening a new wallet instance

I see the wallet full balance, then 0.0 BTC available

**Comment by Transisto** [comment]
The same thing happened when using the wallet to simple send without waiting for more than 5 second for balance to update.

**Comment by InvertedX** [comment]
fixed in [v99.60](https://github.com/Samourai-Wallet/samourai-wallet-android/commit/81c1393564df2d550479adc4942d9daf7f37d7b6)
