### ISSUE TITLE
Crash on RBF Boost transaction fee

### ISSUE THREAD

**Issue by jonathancross** [Samourai-Wallet/samourai-wallet-android#324]
I am getting consistent crashes from Samourai when trying to boost the fee on an RBF transaction.  I tried about dozens of times and it was consistent.

Steps taken:

1. Transaction containing all funds was sent using RBF.
2. After 20 hours it hadn't been mined.
3. I sent new funds into the wallet to a Bech32 address, then tried use those funds to boost the old tx.

Result: app crashed every time I tried to increase the tx fee.

It would get as far as showing me how much the fee would be increased, but as soon as I confirmed, the app crashes.

I have tried offline, with / without trusted node, etc.  No luck.

Please see attached wallet support file encrypted for @SamouraiDev (key `0x72B5BACDFEDF39D7`)

[Samourai_Wallet_support_backup.gpg.txt](https://github.com/Samourai-Wallet/samourai-wallet-android/files/3184598/Samourai_Wallet_support_backup.gpg.txt)

**Comment by Relaxo143** [comment]
Can confirm the same happens to me

**Comment by jonathancross** [comment]
Well, seems there is no interest in even responding, so closing.
