### ISSUE TITLE
Batchsend, change output went to a wrong address

### ISSUE THREAD

**Issue by DanielWeigl** [Samourai-Wallet/samourai-wallet-android#339]
Two consecutive batched sending from the samurai android wallet used a "3...." P2WSH address as an change output, and the wallet does not recognize it as an UTXO:  https://blockchair.com/bitcoin/address/3AZzZWwnXsa5bzfomBu2oXQLaKyWmZ78Qd

The transaction was made friday last week, and I noticed you have made a change/bugfix related to batched sending and change output handling which looks exactly like it would cause this behavior here https://github.com/Samourai-Wallet/samourai-wallet-android/commit/06e2f30c6d2f4d7d84b99925f787c3192d9804b7#diff-d2a57dc1d883fd21fb9951699df71cc7

Any suggestion on how we can recover the now missing change UTXOs? We have the seed for the wallet.

**Comment by DanielWeigl** [comment]
I tried to recover the priv key from the seed with this little (bitcoinj based) script, but was not able to get to the expected address:

```
        byte[] base = MnemonicCode.toSeed(Splitter.on(" ").splitToList("seed words...."), "pwd");
        DeterministicKey bip32Root = HDKeyDerivation.createMasterPrivateKey(base);
        DeterministicHierarchy hierarchy = new DeterministicHierarchy(bip32Root);


        for (int i=0; i<=20; i++) {
            ChildNumber addressIndexChild = new ChildNumber(i, false);

            DeterministicKey key = hierarchy.deriveChild(HDUtils.parsePath("/84H/0H/0H/1"), false, true, addressIndexChild);

            System.out.println(key.getPrivateKeyAsHex() + ": " + key.getPrivateKeyAsWiF(MainNetParams.get()));
            SegwitAddress segwitAddress = SegwitAddress.fromKey(MainNetParams.get(), key);
            LegacyAddress legAddr = LegacyAddress.fromKey(MainNetParams.get(), key);
            System.out.println(segwitAddress);
            System.out.println(legAddr);
            LegacyAddress p2wshAddr = LegacyAddress.fromScriptHash(MainNetParams.get(), ScriptBuilder.createP2WPKHOutputScript(key).getPubKeyHash());
            System.out.println(p2wshAddr);
        }

**Comment by samouraiwallet** [comment]
Hi Daniel, 

If you were impacted by this change address issue please do not hesitate to contact us at support@samouraiwallet.com so we may walk you through the steps needed to derive the private key for those addresses so that you may "recover" those funds. 

Thank you, 

SW

**Comment by DanielWeigl** [comment]
We were able to resolve the issue via support-mail following these instructions:

```
1.) Open Samourai
2.) Navigate to Settings > Troubleshoot > Wallet Indexes
3.) Take note of the numerical value after "84 change"

Once you have noted your index number return to the Troubleshoot screen and select Address Calculator

1.) Select BIP84 Segwit for "Type of Address"
2.) Enter the index number
3.) Select "Change Address"
4.) Select "Display private key" and copy the private key to your clipboard.
5.) You can then attempt to sweep the private key from the toolbar menu on the main balance screen. 
```


Thx for the quick support, :+1:
