### ISSUE TITLE
Transaction shown twice when past midnight

### ISSUE THREAD

**Issue by v0l** [Samourai-Wallet/samourai-wallet-android#342]
Hi,

My transaction is shown twice because it is still pending and occurred yesterday. This would make more sense if it only showed as pending or pending was indicated on the row instead of in the header. 

![signal-attachment](https://user-images.githubusercontent.com/1172179/60451942-e9cf1680-9c5f-11e9-9353-9232ea0c31ae.jpg)

**Comment by v0l** [comment]
Maybe something here: https://github.com/Samourai-Wallet/samourai-wallet-android/blob/544b91b31116ea441d70db207d16055cb4a483cf/app/src/main/java/com/samourai/wallet/home/adapters/TxAdapter.java#L145

Although im no Android dev so im probably wrong 🤔

**Comment by InvertedX** [comment]
> Maybe something here:
> 
> https://github.com/Samourai-Wallet/samourai-wallet-android/blob/544b91b31116ea441d70db207d16055cb4a483cf/app/src/main/java/com/samourai/wallet/home/adapters/TxAdapter.java#L145
> 
> Although im no Android dev so im probably wrong 🤔

no that `-1L` value is just a flag for detecting sections.

issue is in sorting logic.
i m able to reproduce this issue. fix will be included in upcoming releases 
thanks for your valuable feedback 😀👍

**Comment by InvertedX** [comment]
fixed in https://github.com/Samourai-Wallet/samourai-wallet-android/commit/9752ea4492170aa763c1bbd7cc133df84c617dce
