### ISSUE TITLE
F-Droid availability

### ISSUE THREAD

**Issue by xMate420x** [Samourai-Wallet/samourai-wallet-android#351]
Hello. Is there an ETA on when the app will be available from the F-Droid store? I'm tired of compiling from source.

**Comment by Z3ROGRAV1TYx** [comment]
Bump, wondering same.

**Comment by SamouraiDev** [comment]
Following some unfortunate politically-based decisions, we have decided to not work on the F-Droid platform. An alternative means of APK download is being put into place now and will be available very soon.

**Comment by Kartereo** [comment]
@SamouraiDev what political based decisions did they make?  This is the first that I have heard anything bad about them.

**Comment by ndalliard** [comment]
@Kartereo It's probably about F-Droid banning Gab.

**Comment by Kartereo** [comment]
@ndalliard NOTICE: Kartereo has left F-Droid

**Comment by Giszmo** [comment]
FDroid requires apps to be deterministically buildable and to use open licenses. I [tried to verify the Samourai build but failed](https://walletscrutiny.com/posts/2019/11/samourai/). Maybe that is the issue?

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Please provide an F-droid build, who gives a fuck about Gab.

**Comment by SamouraiDev** [comment]
We will be providing downloadable APKs shortly.

**Comment by cyanlemons** [comment]
> politically-based decisions taken by F-Droid

Google takes plenty of politically-based decisions that are magnitudes worse than anything F-Droid has ever done, yet @SamouraiDev, you are more than willing to publish your application on the Play Store.

Who cares if your politics do not perfectly align with F-Droid? This isn't about politics – it's about supporting free and open-source software. Even if you don't agree with them on everything, they are leaps and bounds better than the current proprietary status quo.

**Comment by o-Epictetus-o** [comment]
I am going to have to agree with @cyanlemons . At the time I didn't really understand why f-droid banned gab. Now that I do I will use Fdroid and not gab. Hypocrisy doesn't belong anywhere near FOSS. With that said I know that you probably won't change your political stance. So how will we know when there are updates to the apk if we don't have google services?

**Comment by seniorm0ment** [comment]
I agree with @cyanlemons, I see no reason NOT to put it on F-Droid, if users don't agree with F-Droid's "political views" then they are free to just download the Apk directly. Give users the choice imo.

Anyways to answer @Kartereo 's question about how to know when updates to the apk are available, I believe it can ping to check for new releases and show a notification (similar to how Newpipe does). You could also check manually.

But there is no denying the convenience of F-Droid, and I do not agree with F-Droid's stance on removing Gab, but you have the ability to add in other repos remember, also again I see no reason why not give users the choice of going through F-Droid or downloading the Apk.

**Comment by samouraiwallet** [comment]
Users may download APK directly, build from source, or use Google Play. F-Droid will not be considered.

If you don't like it, get lost.

**Comment by LongJohn-Silver** [comment]
Samourai devs are alt-righters or some shit like that and got butthurted because F-Droid banned their echo chamber, that's why they are so resiliant.

**Comment by gary-host-laptop** [comment]
And still, after all this time, they don't even provide and .apk. such a shame a really good project takes so many bad decisions.

**Comment by samouraiwallet** [comment]
Actually we have been providing an APK for many months. And we released an F-Droid version today. 

Please check the README, we do not use Github anymore, instead we are using our own self hosted Gitlab instance. https://code.samourai.io/wallet/samourai-wallet-android
