### ISSUE TITLE
Connect to Dojo screen

### ISSUE THREAD

**Issue by antonio-fr** [Samourai-Wallet/samourai-wallet-android#353]
On a 1080 line screen (1080 x 2280) Android 9 phone, the *Connect to your Dojo* screen don't have any visible button. To validate it to the next screen (the QR scan) can only be done when touching on the low of "Maintenance control". This zone is very reduced and also not intuitive at all.
  
![Screenshot_20190808_191617_com samourai wallet](https://user-images.githubusercontent.com/7551901/62730014-70290600-ba1f-11e9-827d-4433da3a57fc.jpg)

**Comment by Crazyk031** [comment]
The Dojo pairing screens have been reworked with a new UI so this is no longer an issue
