### ISSUE TITLE
The fee slider makes it very hard to fine tune fees.

### ISSUE THREAD

**Issue by Relaxo143** [Samourai-Wallet/samourai-wallet-android#355]
Fee estimations are often very wrong (even with dojo). If the urgent fee is 100 sats/byte and I want to set it to 2, it's almost impossible. the slightest move of the slider goes from 1 to 10 sats/byte. It would be nice to be able to type the value manually.

**Comment by Kaloyan15** [comment]
I agree with the commenter above, the slider is too confusing to use and a hassle to set a precise fee.

**Comment by tuzumbear** [comment]
I wanted to buy an Itunes card at bitreffil, for example. They demanded a mainerfee of 6st/b. Unfortunately that was not possible. The slider went at most up to 1.5 sat/b. It would be really nice if you could enter a fixed height in addition to the slider

**Comment by jodobear** [comment]
there should be an input field for manual entry of fees. The slider is RIDICULOUS!

**Comment by Relaxo143** [comment]
> there should be an input field for manual entry of fees. The slider is RIDICULOUS!

The Project is now maintained here: https://code.samourai.io/wallet/samourai-wallet-android
You might want to voice your opinions there.

**Comment by Crazyk031** [comment]
Fee slider has had improvements to correct this issue
