### ISSUE TITLE
[Feature Request] Unlock with fingerprint

### ISSUE THREAD

**Issue by trackktor** [Samourai-Wallet/samourai-wallet-android#366]
Hello,
It is me again.

With a lots of bank app it is possible to unlock with fingerprint instead of scheme or pin.
It is REALLY convenient and really improve the user experience.

Maybe it could be added to samourai ? 

To go further you could add a fingerprint check for send or any dangerous operations if there is a fingerprint sensor (same idea as Feature request: ask for PIN before sending a transaction).
 It could be particularly usefull when you are switching between apps and Samourai stay open. 

Here, two examples of existing bank app 
![20190915_213411](https://user-images.githubusercontent.com/55330354/64926689-c51b2180-d800-11e9-992a-c2333dad30a7.jpg)
![Screenshot_20190915-211822_CMSO](https://user-images.githubusercontent.com/55330354/64926690-c51b2180-d800-11e9-9606-aff75020f338.jpg)

**Comment by natedalliard** [comment]
It may be convenient, but it's considered **insecure**. That's probably enough reason for the samourai wallet developers not to implement it.

**Comment by SamouraiDev** [comment]
We will not be using any biometric capabilities in Samourai Wallet.

**Comment by 21m** [comment]
Why don't we close this issue?

**Comment by Sea-Worker9552** [comment]
I think this is a sad oversight. If our goal is to maximize security, then at least a passphrase option should be allowed. A 5-6 digit PIN just spells trouble. I wonder how many people just use their birthday or a significant other's birthday as the PIN.

I really suggest reading the white paper on TouchID from Apple or documentation for Android developers. Your actual fingerprint images aren't stored in the phone itself, and there's no way to extract a fingerprint.
