### ISSUE TITLE
App crash on QR code scanner open if previously denied camera permission

### ISSUE THREAD

**Issue by alxkzmn** [Samourai-Wallet/samourai-wallet-android#373]
### App version
0.99.88
### Steps to reproduce

- When asked for camera permission, deny
- When on home screen, try to open QR code scanner

**Comment by alekskuzmin** [comment]
#374

**Comment by SaiyajiiN** [comment]
App still crash on my phone.

**Comment by Crazyk031** [comment]
This issue has been fixed within the wallet
