### ISSUE TITLE
Failed to verify the app on GooglePlay

### ISSUE THREAD

**Issue by Giszmo** [Samourai-Wallet/samourai-wallet-android#376]
At the time of writing [this article](https://walletscrutiny.com/posts/2019/11/samourai/) we failed to verify the app released on Google Play. I hope we can resolve the issues we ran into soon.

**Comment by zeven74** [comment]
The lack of response is not building trust!!!! I am now switching to mycelium

**Comment by SamouraiDev** [comment]
See our response on twitter.

**Comment by Giszmo** [comment]
@zeven74 the tweet is now also linked in the article.
