### ISSUE TITLE
Output wrongly shown as unspent

### ISSUE THREAD

**Issue by whizz** [Samourai-Wallet/samourai-wallet-android#379]
I have imported an xpub into Sentinel and even though I know it's empty, Sentinel shows some balance. So I tried importing the BIP39 seed it into Samourai too and the same problem shows. Samourai show some balance in the wallet. For some reason, Samourai (and Sentinel) consider ff08530b4eca88a7ebdf1e628355caee8fa8004e8173251c1c42776d70ece2c5:0 to be unspent.

**Comment by SamouraiDev** [comment]
Issue is resolved. Thank you.

**Comment by whizz** [comment]
Confirmed fix, thank you for a quick response and for your work on Samourai!
