### ISSUE TITLE
Add app to F-Droid store

### ISSUE THREAD

**Issue by LilChange** [Samourai-Wallet/samourai-wallet-android#38]
F-Droid is a decentralized Android app store that is privacy conscious and only allows open source apps to be added. Learn more:

https://f-droid.org

And here are some developer docs if you want to self host the build with your own F-Droid repo:

https://f-droid.org/wiki/page/Setup_an_FDroid_App_Repo#Real_World_Setup

This should be pretty easy since you are open source. Hope you are up for it.

**Comment by SamouraiDev** [comment]
We are for it. This is on our roadmap for 1.0.

**Comment by LilChange** [comment]
Excellent to hear 😀

**Comment by amicrod** [comment]
Can you please reopen this issue? I think dev builds for fdroid are important as it is the best way we can do testing on lineageOS or more security conscious Copperhead.  This will also ensure that we stay more up to date (rather than just using the signed apk)

**Comment by IzzySoft** [comment]
How far away is that roadmap you announced over a year ago, @SamouraiDev? There's already an [open request](https://gitlab.com/fdroid/rfp/issues/712) at F-Droid, but we cannot include your app because of "binary components" (JARs in `app/libs/`) and non-whitelisted Maven repos (`https://dl.bintray.com/magnusja/maven`). Any chance you can get that cleared?

**Comment by SamouraiDev** [comment]
You can build from source in the meantime.

**Comment by IzzySoft** [comment]
Afraid not, due to the issues I mentioned in my previous post: That Maven repo is still there, and so are the JAR. F-Droid doesn't allow binary components, all must be built from source.

**Comment by SamouraiDev** [comment]
I meant you as an individual, not F-Droid. We'll get to it.

**Comment by IzzySoft** [comment]
OK, thanks! And I was asking for F-Droid, not for me – I'm no dev, I've got no dev environment nor experience :wink:

**Comment by IzzySoft** [comment]
Any news on this, @SamouraiDev? The issue at F-Droid is still stalled. And I'm still no dev, so I cannot build from source in the meantime :wink:
