### ISSUE TITLE
App keeps reusing P2PKH change addresses

### ISSUE THREAD

**Issue by Mikadily** [Samourai-Wallet/samourai-wallet-android#381]
About every second time when doing a tx to P2PKH type of address the change address is the one that has already been used, therefore leaking privacy. Stonewall on.

This is my address view when importing seed with Electrum after been using it with Samurai wallet for some time:
![2020-01-17_10-40](https://user-images.githubusercontent.com/2736855/72577826-6d5c0680-3917-11ea-9fd0-f4ef5d61bda1.png)

**Comment by SamouraiDev** [comment]
We have been unable to replicate this. Can you provide additional details?

**Comment by Mikadily** [comment]
It seems that it stopped from happening since 1 month ago, I can't replicate it anymore.
