### ISSUE TITLE
Wrong amount scanned from payment request

### ISSUE THREAD

**Issue by theihor** [Samourai-Wallet/samourai-wallet-android#39]
I've encountered an issue when the wallet makes a transaction with the amount that is less than specified in payment request QR code.
As far as I can tell it may appear when display units are not BTC.

Steps to reproduce:
1. Change display units to mBTC.
2. Scan QR code of payment request with a precise amount (to satoshi).
3. Compare the amount in the constructed transaction with requested one.

For example, when a request is for 1.23456 mBTC, the scanned amount is 0.0012 BTC and display units are changed back to BTC.

**Comment by SamouraiDev** [comment]
This issue has been fixed in a previous release.
