### ISSUE TITLE
Crashing when setting trusted node

### ISSUE THREAD

**Issue by Moller40** [Samourai-Wallet/samourai-wallet-android#391]
Does not matter if it's a valid node or not. Can trigger the crash by setting this:

IP address: 111.111.111.111
Port: 8332
rpc user name: name
rpc user password: pass

```
02-19 11:32:12.772 18309 18922 E AndroidRuntime: FATAL EXCEPTION: Thread-9
02-19 11:32:12.772 18309 18922 E AndroidRuntime: Process: com.samourai.wallet, PID: 18309
02-19 11:32:12.772 18309 18922 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
02-19 11:32:12.772 18309 18922 E AndroidRuntime: 	at com.samourai.wallet.JSONRPC.JSONRPC.doRPC(JSONRPC.java:255)
02-19 11:32:12.772 18309 18922 E AndroidRuntime: 	at com.samourai.wallet.JSONRPC.JSONRPC.getNetworkInfoAsString(JSONRPC.java:220)
02-19 11:32:12.772 18309 18922 E AndroidRuntime: 	at com.samourai.wallet.SettingsActivity2$42$1.run(SettingsActivity2.java:1178)
02-19 11:32:12.772 18309 18922 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
02-19 11:32:12.772 18309 18922 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: org.apache.http.impl.client.DefaultHttpClient
02-19 11:32:12.772 18309 18922 E AndroidRuntime: 	... 4 more
02-19 11:32:12.775  1749  9193 I am_crash: [18309,0,com.samourai.wallet,950550084,java.lang.ClassNotFoundException,org.apache.http.impl.client.DefaultHttpClient,JSONRPC.java,255]
```

Using Android 10. Maybe that triggers this problem?

Samourai version: 0.99.88

**Comment by Moller40** [comment]
Think the solution is here: https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p
Perhaps I do a PR.

**Comment by pajasevi** [comment]
Just FYI: setting a trusted node is now discouraged and this option should be removed in future release in favor of Dojo.

**Comment by davterra** [comment]
I'm experiencing this issue as well. 
What if I'm already running a full node and don't want to bother with Dojo? How can I connect my wallet?

**Comment by nicheosala** [comment]
I still cannot connect my Samourai Wallet 0.99.91 to my Bitcoin Core full node.
I go to Settings->Transactions->"Set trusted node". After entering the useful information, as soon as I click "ok", the app crashes.

**Comment by likewhoa** [comment]
> I still cannot connect my Samourai Wallet 0.99.91 to my Bitcoin Core full node.
> I go to Settings->Transactions->"Set trusted node". After entering the useful information, as soon as I click "ok", the app crashes.

You shouldn't be doing this anymore as stated above this feature will be deprecated soon. The method is different now. You pair your wallet with your dojo instead. see https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_setup.md#pairing it's recommended to do this with a fresh wallet.

**Comment by Crazyk031** [comment]
Trusted node has been removed from the wallet, Dojo is the required backend for the wallet now
