### ISSUE TITLE
Show fees in BTC with 8 decimals (full precision)

### ISSUE THREAD

**Issue by Transisto** [Samourai-Wallet/samourai-wallet-android#414]
![image](https://user-images.githubusercontent.com/388716/81999221-75585880-9622-11ea-8c8b-2cbe02783061.png)

It appeared to me that Stonewall option was cheaper because the wallet trimmed the lat 0 from the total fee.

**Comment by miguelm9** [comment]
Can you please give any more details?

**Comment by Transisto** [comment]
Above is 8510 Sats I thought it was 851 Sats for a moment. There's no need
to trim trailing zeros. Especially for fees which are relatively small
amounts.

**Comment by miguelm9** [comment]
Alright, I'll try give it a fix, although I have very little idea of how does the code work (yet)

**Comment by Crazyk031** [comment]
This is currently being worked on, please note that the Samourai repo has moved to code.samourai.io

**Comment by Crazyk031** [comment]
This has been implimented wallet wide, all displays of btc show the full 8 decimal points
