### ISSUE TITLE
BUG: Wrong display of `Miner Fee Rate`

### ISSUE THREAD

**Issue by jodobear** [Samourai-Wallet/samourai-wallet-android#415]
In the tx detail window I see wrong fee under `Miner Fee Rate` but the `Miner Fee Paid` displays correct fee aggregate. This is true of pretty much every tx I have made with more than 1 sat/byte.

I'm not sure why and how can this be possible, It's quite random but it's always lesser than the fee I paid, for example, I made a tx today at ~12 sat/byte and I see 9 sat/byte, previously I made a tx ~5 sat/bye and i see 3 sat/byte. Though the total fee paid is correct.

This is very confusing and somewhere raises serious perception issues with questions like, "Is Samourai wallet itself taking a fee on every tx?" - i know that's not the case, but try explaining it to someone who doesn't understand Samourai or Bitcoin and is new to the scene.

**Comment by Crazyk031** [comment]
This issue is being looked into currently, shooting for a resolution in the next release. Please note that the repo has been moved to code.samourai.io. Thank you for the report!

**Comment by Crazyk031** [comment]
Fee rate display has been updated as of a couple releases ago, thank you for the report.
