### ISSUE TITLE
Switching between networks and using different blockchain explorer

### ISSUE THREAD

**Issue by uridium** [Samourai-Wallet/samourai-wallet-android#419]
Hi @samouraiwallet 
First off, good job with your product! It's my favorite mobile wallet - very intuitive and focused on privacy.
Now, are you planning on implementing a feature that supports switching back and forth between mainnet and testnet? It's really inconvinient to reinstall the app only to select desired network. And it seems that only apk version allows to do that.
Also, would it be possible for the end user to define other explorer than https://blockstream.info? For example https://www.blockchain.com/explorer

**Comment by Crazyk031** [comment]
No reason to uninstall the app to switch between a testnet & mainnet wallet, you can do this by secure erasing the wallet you currently have and recovering via a saved encrypted backup. Plans are in the works to improve the explorer function of the wallet. Also please note that the repo has been moved to code.samourai.io
