### ISSUE TITLE
Transaction is not broadcast

### ISSUE THREAD

**Issue by raedah** [Samourai-Wallet/samourai-wallet-android#42]
Shows Transaction Sent msg on screen, then app crashes. I launch the app again and the transaction still shows in the list, but does not show in the network mempool when looking at a blockexplorer. This may be being caused because the wallet spent from a not yet confirmed transaction. I can see the first unconfirmed transaction in the mempool, but not the subsequent transactions that spent the unconfirmed change.

No work around:
- no way to select to rebroadcast the transaction
- no way to copy the rawtransaction to manually broadcast it elsewhere
- unable to get priv keys, unspent output list only shows the outputs the wallet thinks are unspent, which are ones that are from transactions which are not on the blockchain.

**Comment by SamouraiDev** [comment]
"Transaction Sent" toast displays after broadcast and success return status. Can you post tx hash?

**Comment by raedah** [comment]
I cant post the tx hash and that would disclose personal data. I did three transactions that are all unconfirmed. The first one shows on a blockexplorer as unconfirmed. That later two do not show on the blockexplorer at all.

**Comment by SamouraiDev** [comment]
Raw transaction export cabability included in next update.

**Comment by raedah** [comment]
Will the wallet attempt to rebroadcast the transaction after some interval of time if it has not confirmed?

**Comment by SamouraiDev** [comment]
On the roadmap.

**Comment by raedah** [comment]
My preference would just be for the ability to select to rebroadcast manually, rather then it being automatic.
