### ISSUE TITLE
backup file is overwritten by default setting

### ISSUE THREAD

**Issue by raedah** [Samourai-Wallet/samourai-wallet-android#43]
The default setting is to 'Autosave backup to device storage'. In the case where the user is trying to recover their wallet from the backup file and samouri does not initialize properly, such as creating a wallet that does not properly show any transactions or balances, the next thing that happens is that the default autobackup setting will overwrite and destroy the good backup file on disk.

**Comment by SamouraiDev** [comment]
Users are invited to take a backup manually via the app menu on the balance screen. The backup on device is there in the event that the user needs to restore wallet to existing seed and that can always be overwritten by the backup that the user has put aside.
