### ISSUE TITLE
Optional fiat values

### ISSUE THREAD

**Issue by leto** [Samourai-Wallet/samourai-wallet-android#430]
It would be nice to have a defaulted to OFF option to show fiat values in a selection of currencies. Coingecko.com supports over 40 fiat currencies including Gold and Silver (XAU + XAG) to render values in. It's a simple and free JSON web api.

If this is something that is desired, I could help with it. I have implemented this feature for a full node wallet.

**Comment by clarkmoody** [comment]
Fiat was intentionally removed from the wallet. It will probably not make its way back in.

**Comment by leto** [comment]
@clarkmoody thanks for the heads up, closing this as the proper place for issues is Gitlab

**Comment by leto** [comment]
@clarkmoody and just saying, Gold+Silver are not fiat, and I would like to see my balances rendered in other "real money" 😎
