### ISSUE TITLE
How to refresh list of transactions using offline mode?

### ISSUE THREAD

**Issue by notf0und** [Samourai-Wallet/samourai-wallet-android#435]
When samurai wallet is on offline mode, you can broadcast a transaction with the inputs received in another transactions, so it means at some point samurai has been online. But what happens when you receive bitcoins using sentinel? Since the list don't get updated on samurai means that you cannot send this new bitcoins unless you become online on samurai. There is a way to pass the list of transactions hold on sentinel to samurai?

**Comment by Crazyk031** [comment]
This is something that will be implimented in the wallet in the future, being able to use Sentinel to update the offline wallet
