### ISSUE TITLE
Support other block explorers

### ISSUE THREAD

**Issue by raedah** [Samourai-Wallet/samourai-wallet-android#44]
https://tradeblock.com/bitcoin/explorer/
https://live.blockcypher.com/btc/

**Comment by SamouraiDev** [comment]
We need to evaluate which block explorers will remain on or provide access to the valid consensus chain. Any block explorer that respects those conditions will be considered for inclusion.

**Comment by SamouraiDev** [comment]
We now support blockcypher, as of release 0.97.01.

**Comment by SamouraiDev** [comment]
We have added OXT to the block explorer selection.
