### ISSUE TITLE
Showing zero balance after restoring wallet

### ISSUE THREAD

**Issue by PestToast** [Samourai-Wallet/samourai-wallet-android#448]
I regularly delete and restore my wallet in the app and I have never had issues before. When I tried this time, no transactions are showing in the app. I verified that there are still utxos with old wallet addresses. I verified that the paynym is the same. Everything should be working, but it's just not able to pull the info for some reason.

**Comment by NuiceT** [comment]
This happened to me as well, as there's a bug where the post mix-change and fund wallet are somehow swapped. Workaround would be to restore your wallet in Sparrow with your 12 words with the derivation path `m/84'/0'/0'`
