### ISSUE TITLE
Add ARS FIAT currency

### ISSUE THREAD

**Issue by notf0und** [Samourai-Wallet/samourai-wallet-android#45]
I would like if you could add ARS currency.
I usually use the following APIs to do this:

https://www.bitinka.com.ar/api/apinka/ticker?format=json
https://api.satoshitango.com/v2/ticker
https://www.ripio.com/api/v1/rates/

Ripio.com could be unusable at the next month because they are B2X supporters (The will follow the hasrate to determine wich is BTC).

I can write this and make a PR to add one or more of this providers.

Another way to do this can be using the Bitfinex API to get price in USD and then another API to calculate the USD/ARS conversion.

I'ts possible?

**Comment by SamouraiDev** [comment]
Adding new currencies is not high on our list of priorities right now. When it does come back to the forefront as a priority we will be working with one universal rate supplier in order to streamline the implementation. Thank you.

**Comment by mr-e-** [comment]
This app is able to load pretty much every pair from every exchange: https://github.com/mobnetic/BitcoinChecker. Maybe you could fork some code from them:D

However, I see that you already have BitcoinAverage integration, it would be super helpful if you could at least load their currencies from their api.

**Comment by SamouraiDev** [comment]
We stopped using BitcoinAverage a couple of months ago.

**Comment by mr-e-** [comment]
Oh wow, what is the reason for that? I've always considered BitcoinAverage to be the "real" price.

**Comment by SamouraiDev** [comment]
As I recall there were some changes regarding the terms of use of their API so we decided to continue without them. We've always had a preference for the exchange rates provided by BTC-e (now WEX) and Localbitcoins. We'll have a wider selection based on a universal provider early next year.
