### ISSUE TITLE
[UI][Minor] Sweep private key: Back button not working

### ISSUE THREAD

**Issue by lclc** [Samourai-Wallet/samourai-wallet-android#46]
Click 'Sweep private key' -> Shows modular window with no direct way back to the home screen (back button is not working)

Samourai Version: 0.96.01 (Playstore)
Device: Nexus 5x
Android Version: 8.0.0

**Comment by SamouraiDev** [comment]
Will patch asap. In the meantime, just move ahead to 'scan' and then use back button.

**Comment by SamouraiDev** [comment]
Patched in release 0.96.02.
