### ISSUE TITLE
App crashes on send segwit to segwit

### ISSUE THREAD

**Issue by notf0und** [Samourai-Wallet/samourai-wallet-android#50]
I'm trying to send from a Segwit address to another, but when I send, the app crashes and ask to reopen or leave closed. Both addresses belong to the same wallet, so expected is to see an output transaction and an input transaction at the same time. The transaction is not broadcasted, so the funds are locked until this issue will closed.

**Comment by SamouraiDev** [comment]
The app does many segwit-to-segwit transactions currently because when spending to a P2SH address, Samourai will create P2SH-P2WPKH outputs for change amounts. The issue is either device dependant or dependant on the characteristics of tx being made. Perhaps you can try turning off tx broadcasting (settings->transactions) and dump the hex of the tx you are attempting so that can be checked out.

**Comment by barsnadcat** [comment]
App crashes after broadcasting transaction from segwit address to any address. Right after confirmation screen showing send amount and fee. MotoG 1 gen, Android 5.1. Here is transaction that crashed app: https://www.smartbit.com.au/tx/2e8b2103710264ed6155694e6b0323f9850c9229ec8a5f1e3976d9d7b06d0b1a

**Comment by SamouraiDev** [comment]
Thank you for the bug report but that is not a Segwit tx. Appears to be P2PKH->P2PKH. We will look into it.

**Comment by notf0und** [comment]
The follow screenshots are when I'm trying to send segwit to segwit. Same error when disabling broadcast.
![0](https://user-images.githubusercontent.com/2713486/31956180-016cc08c-b8c1-11e7-9f7d-cb2bce6c0e09.png)
![1](https://user-images.githubusercontent.com/2713486/31956186-08450cc0-b8c1-11e7-9ad2-c62343bbac20.png)
![2](https://user-images.githubusercontent.com/2713486/31956193-110bca56-b8c1-11e7-96f6-4db61a92a8f5.png)

**Comment by SamouraiDev** [comment]
The fact that the transaction is going out to a Segwit address is not a factor here as the app sees no difference between P2SH outputs and P2SH-P2WPKH outputs.

**Comment by SamouraiDev** [comment]
All support issues should be reported to support@samouraiwallet.co. Thank you.
