### ISSUE TITLE
Loss of Tor privacy when tapping on a transaction

### ISSUE THREAD

**Issue by mr-e-** [Samourai-Wallet/samourai-wallet-android#51]
Since the transaction opens up in a chrome browser it is not directed through Tor. Therefore anything you were trying to do through Tor has been immediately unmasked by your ISP. A resolution would be to offer an in app transaction browser that loads the data through Tor.

**Comment by SamouraiDev** [comment]
This is on our to-do list. Tor functionality will be enhanced and an in-app tx viewer will be integrated. For the time being, VPN access would work fine with Chrome.

**Comment by SamouraiDev** [comment]
In-app transaction view has been released. Tor overhaul being done shortly in advance of Whirlpool release.
