### ISSUE TITLE
Loss of wallet privacy if Orbot is not running at the time of starting the wallet

### ISSUE THREAD

**Issue by mr-e-** [Samourai-Wallet/samourai-wallet-android#52]
For some reason unknown my Orbot stopped running. I didn't notice this until I tapped on the Samouri app. What I saw was that Samouri does attempt to start Orbot automatically BUT it also disabled the Tor button and continued to load the data on the clear. This would mean that the entire download of my wallet history was exposed and all privacy done through Tor was immediatly lost. Critical defect IMO. If Tor was enabled then the wallet should NEVER try to load anything via clearnet. There should probably even be a warning about this if the user attempts to disable it.

**Comment by SamouraiDev** [comment]
Orbot is not ideal. We are looking at ways of either improving its use or replacing it with something in-app.

**Comment by mr-e-** [comment]
Perhaps, but given the importance that this app places on privacy, at the very least it should display an error rather then just disabling Tor and leaking all your data...

**Comment by jmliz** [comment]
Confirmed issue. When creating a new wallet it starts querying the address balance automatically via clearnet (although the balance should be 0 for new wallets :/). The settings cannot be accessed during that initial queries or when the device is offline. Other wallets let the user create wallets offline and change setting to tor only. 

@SamouraiDev Maybe Orbot is not ideal but not using it is worst. And the socks5 proxcy works well (as it is used right now). It is the vpn app mode that's unreliable, but samourai does not use it. thjis should be top prio, imo.

**Comment by SamouraiDev** [comment]
A new Tor lib is now in use, as of v0.99.25.
