### ISSUE TITLE
Starting the app via the launcher will always reload all transactions, while tapping from multitask window does not

### ISSUE THREAD

**Issue by mr-e-** [Samourai-Wallet/samourai-wallet-android#53]
This wouldn't be too much of a hassle of the Tor downloading didn't take so long. But I find myself constantly having to hunt for the app in my multitask window instead of using the icon on my home screen in order to prevent having to wait 30 second+.

**Comment by SamouraiDev** [comment]
This is deliberate, for the time being. It might be changed for v1.0.

**Comment by mr-e-** [comment]
Hmm, what is the reason for that? If the app is already ready running normally it's an Android app practice to just use the existing activity with it's restore state. 

Also, Is there a reason the transaction data is cached so that it can be displayed and interacted with immediately, while loading the data in the background? Cache-first approach?
