### ISSUE TITLE
Application crashed after sending a transaction and transaction list was loading for a while. 

### ISSUE THREAD

**Issue by mr-e-** [Samourai-Wallet/samourai-wallet-android#54]
Unfortunately I am not able to reproduce this crash but it basically hung on loading transactions for a long time and eventually crashed. I had Tor mode enabled.

**Comment by goodmorningcmdr** [comment]
This happened to me this morning. It didn't hang on loading transactions, however, and I did not have Tor mode enabled.

**Comment by SamouraiDev** [comment]
All support issues should be reported to support@samouraiwallet.co. Thank you.
