### ISSUE TITLE
Balance not diplayed on non segwit adresses

### ISSUE THREAD

**Issue by notf0und** [Samourai-Wallet/samourai-wallet-android#55]
I've created a wallet with Samourai and get a non segwit address.
Made a transaction to this adddress but i can't see the balance on Samourai.
Tested again to receive under a segwit address and balance on this address is displayed ok.
Imported Mnemonic+passphrase on Copay Bitcoin Wallet and the balance is displayed ok for non segwit adresses.

**Comment by SamouraiDev** [comment]
We would appreciate that tech support requests go to support@samouraiwallet.com and we will handle it there. Thank you.
