### ISSUE TITLE
The app does not ask for PIN until the app is closed. 

### ISSUE THREAD

**Issue by Bluethf** [Samourai-Wallet/samourai-wallet-android#56]
The app only asks for PIN when it's exited by pressing the 'back key' or the recent apps have been closed. 

- If we directly go to home screen from the app and open the app using the icon it does not ask for the PIN again. 

- If we press the recents key and switch to another app and then switch back to Samourai Wallet again then it does not ask for the PIN again. 

- I tried to test if there is a condition to ask for the PIN after the app has been in background for 'x' time but it didn't ask me to enter the pin after I opened it after 15 minutes from icon and recent apps.

**Comment by SamouraiDev** [comment]
It should ask for the PIN after the timeout has elapsed.

**Comment by Bluethf** [comment]
How long is the timer? 

I think the PIN should be added every time the app comes back from the background for increased security.

**Comment by SamouraiDev** [comment]
Timer is set to 15 minutes, currently.

**Comment by Bluethf** [comment]
Maybe set it to 1 minute for improved security? 
Thanks.
