### ISSUE TITLE
Pressing increase tx fee button does not work

### ISSUE THREAD

**Issue by mr-e-** [Samourai-Wallet/samourai-wallet-android#57]
I just tapped on my tx and was presented with a dialog offering to increase my tx fee. When I press the button the dialog dissapears but nothing seems to happen. I checked the transaction on a block explorer and the fee appears to be the same as it was previously.

**Comment by SamouraiDev** [comment]
Please open support tickets over at support@samouraiwallet.com rather than here and, if possible, supply a bit more information such as a tx hash. Thank you.

**Comment by mr-e-** [comment]
It worked after killing the app and restarting, pretty sure I've seen this before, so it's definitely a bug with the app.

**Comment by KibbledJiveElkZoo** [comment]
I have experienced this too, in fact it happens every time after I bring up the INCREASE TX FEE option for the first time.
