### ISSUE TITLE
Use segwit for change addresses.

### ISSUE THREAD

**Issue by mb300sd** [Samourai-Wallet/samourai-wallet-android#59]
I've noticed that the change addresses are non-segwit, so we only get the fee advantage for the first spend on a new input.

**Comment by SamouraiDev** [comment]
Change outputs match the type of address of the spending output. If you spend to a P2SH address, all change outputs will be segwit outputs.

**Comment by mb300sd** [comment]
I'd suggest adding an option, maybe right under the BIP126 option with warnings to allow the user to prioritize fees vs privacy. This seems to be the best wallet with segwit support at the moment.

Also, an option to have multiple accounts would be nice ;) Maybe with the privacy settings per account.

**Comment by SamouraiDev** [comment]
Until we reach v1.0, this is still a work in progress. We are considering different options and app settings.

**Comment by SamouraiDev** [comment]
Now optional as of v0.97.13.

**Comment by janklosowski** [comment]
> Change outputs match the type of address of the spending output.

Unfortunately, that makes using Segwit wallet a _Pyrrhic victory_ in the current environment where Segwit addresses are still rare.

**Comment by SamouraiDev** [comment]
Now optional as of v0.97.13 if user favors segwit fee discounts over privacy.

**Comment by vv01f** [comment]
I'd regard this as solved since we have the option. Any other plans short term why it's kept open?

**Comment by SamouraiDev** [comment]
It's a commonly asked question and I'd like it to remain visible.
