### ISSUE TITLE
Feature Request: Ability to Customise "INCREASE TX FEE" Rate/Amount

### ISSUE THREAD

**Issue by KibbledJiveElkZoo** [Samourai-Wallet/samourai-wallet-android#60]
I very much would like the ability to customize the fee rate/amount of the new fee when using the "INCREASE TX FEE" feature on a transaction.

**Comment by SamouraiDev** [comment]
Tap on the text area to the right of the fee button and you will be able to enter a custom fee amount expressed in sat/b.

**Comment by KibbledJiveElkZoo** [comment]
I think that is for a transaction that is newly being created in the Send area/screen; I am referring to when a transaction is already formed, broadcast, and shown in the wallet and a person is attempting to increase the transaction fee because the transaction is not being confirmed.

**Comment by SamouraiDev** [comment]
Sorry, misunderstood. Yes, that functionality is planned for in a future update.

**Comment by KibbledJiveElkZoo** [comment]
Thanks for that.  This feature would be just the thing that would make me use Samourai over my favorite other wallets, with this feature Samourai Wallet would include everything I need from all the other wallets and an extra special feature that none of them have that I would use a lot!

**Comment by KibbledJiveElkZoo** [comment]
Any insight into a time scale that custom increase fee rate amounts might be available for Samourai Wallet?
