### ISSUE TITLE
Return to Home Screen from Receive & Send Screens by Touching "Samourai" Text in Upper Left

### ISSUE THREAD

**Issue by KibbledJiveElkZoo** [Samourai-Wallet/samourai-wallet-android#61]
I think it would make sense, when on the Send and the Receive screens, for touching the word "Samourai" in the upper left corner of the screen/app, to bring/return the user to the "home page/screen".

**Comment by samouraiwallet** [comment]
This will be the case in upcoming UI update builds. Thanks for the suggestion :)
