### ISSUE TITLE
Support for Bech32 SegWit addresses

### ISSUE THREAD

**Issue by notf0und** [Samourai-Wallet/samourai-wallet-android#64]
Hi, I'm trying to send bitcoins to Bech32 addresses generated by the latest version of Electrum, but Samourai apparently don't recognize, and send button never appears.

**Comment by SamouraiDev** [comment]
We have not yet rolled out support for bech32. Development is advanced but unfinished. https://github.com/Samourai-Wallet/samourai-wallet-android/tree/develop/app/src/main/java/com/samourai/wallet/segwit/bech32

**Comment by SamouraiDev** [comment]
Available in v0.97.10.
