### ISSUE TITLE
Bug: third HD account not imported.

### ISSUE THREAD

**Issue by dammkewl** [Samourai-Wallet/samourai-wallet-android#65]
I have a 12word seed imported from another wallet, the first and second HD accounts are imported but not the third.

The paths are as follows:

First: m/44'/0'/'0/0/4
Second: m/44'/0'/1'/0/3
Third: m/44'/0'/2'/0/1

I have yet to dive into the meanings of these paths myself, but that's what my previous wallet shows me as the current status for each account.

**Comment by dammkewl** [comment]
Thanks for the tip!

Could I make the request here for in the short term to extend support to importing accounts up to the first one with no TX's? I understand you have your internal roadmap and wouldn't wish to divert devtime away from that, just curious if it would fit in there.

Rant: I'd expect for implementing such a feature request, the "import" side of this to be (re)usable for whatever is planned ahead in multi-account support, but I do fear what the "spending" side of this could architecturally entail.

**Comment by SamouraiDev** [comment]
We have already discussed changing the wallet restore to look at all populated accounts so that is in the cards for our near-term modifications.

**Comment by dammkewl** [comment]
Thanks for the help and thanks again for this great product. Keep up the good work!
