### ISSUE TITLE
Feature request: Fingerprint access

### ISSUE THREAD

**Issue by vmavromatis** [Samourai-Wallet/samourai-wallet-android#67]
Would love that! There are plenty of android libraries for this like reprint.

Thank you for all your hard work, you guys are awesome.

**Comment by SamouraiDev** [comment]
We are looking into different types of access control beyond PIN entry. Personally, I'm not sold on the security/privacy of fingerprint access or face recognition.

**Comment by vmavromatis** [comment]
Is this a security concern? Most banking apps support fingerprint access and honestly, it's quite convenient. Most stats put it around [99.8% accuracy](https://www.forensicmag.com/news/2011/05/fingerprint-evaluations-998-percent-reliable)* and the remaining 0.2% has to overlap with the person who stole your phone so chances are approaching zero. 


Re. face recognition I would agree, the numbers are significantly lower and vary depending on race. I would not trust it as a user.

*: Also remember Apple's claims about 1 in 50,000 attempts being wrong.

**Comment by SamouraiDev** [comment]
Not so much an issue with accuracy but more to do with where those fingerprints wind up and who has access to them. I'm much more at ease using fingerprint access on my Nexus 5X/Copperhead OS than on a Google Apps device, for example.

**Comment by vmavromatis** [comment]
Yeah fair point, these are security concerns for all phones, depending on OS/setup. I'm happy with lineageOS/microG for such reasons. Anyone who trusts putting info on the 'cloud' is fucked. This is the type of convenience people should avoid.

**Comment by Bluethf** [comment]
@SamouraiDev How about U2F Security USB key through OTG? People can easily make their own security key through GitHub. https://github.com/conorpp/u2f-zero

**Comment by Technifocal** [comment]
@SamouraiDev While I understand your concern with privacy, I believe most users already utilise the fingerprint option (I know that everyone I know who owns a smartphone with fingerprint detecting hardware already utilises it extensively), surely integrating with the [Android Fingerprint API](https://developer.android.com/about/versions/marshmallow/android-6.0.html) (Which is what pretty much every app, except a few (like Lastpass) uses, including banking apps) doesn't add any inherent privacy loss, just utilises already existing privacy loss, if that makes any sense. Basically, "I've already given up my privacy to Google by registering my fingerprints, why not let me use it on one more app".

**Comment by SamouraiDev** [comment]
I understand the reasoning but, given that very reasoning, would prefer to refrain from such an approach.

**Comment by Technifocal** [comment]
Fair enough, and thank you for at-least considering it. I do still believe it should be the user's choice how they authenticate (or whether they authenticate at all), and I would genuinely appreciate fingerprint support. However, it's your app and you're free to do what you like with it. Thank you once again for the software :+1:

**Comment by dlfsjdfjodifjsodifjsdo** [comment]
is there any evidence to suggest fingerprint data can be compromised? also having fingerprint + passphrase + passcode + 2FA OTP all at once would be nice for peace of mind

**Comment by SamouraiDev** [comment]
No plans for fingerprint access.

**Comment by dmo580** [comment]
I think this is a sad oversight. If our goal is to maximize security, then at least a passphrase option should be allowed. A 5-6 digit PIN just spells trouble. I wonder how many people just use their birthday or a significant other's birthday as the PIN.

I really suggest reading the white paper on TouchID from Apple. Your actual fingerprint images aren't stored in the phone itself, and there's no way to extract a fingerprint.
