### ISSUE TITLE
Force communication to go through Tor

### ISSUE THREAD

**Issue by dmp1ce** [Samourai-Wallet/samourai-wallet-android#7]
I just started using Samourai, so I might be missing something, but is there any feedback to the user on when Tor is connecting or when it is sending data?

I want to make sure that Tor doesn't turn off without me knowing it. I dealt with a related issue for awhile with Mycelium wallet until they implemented a Tor hidden service which their wallet was required to use when Tor was turned on. I would rather not be able to send a transaction than send a transaction on the clear net without me knowing it happened.

**Comment by SamouraiDev** [comment]
Our Tor implementation has been changed recently. The Samourai users chooses to route through Tor or not. If traffic is routed through Tor it is sent via Socks5. The Orbot indicator shows whether or not traffic is being routed through Tor. Future updates will bind Tor more closely to the app.
