### ISSUE TITLE
QRCode causes crash on low-res devices

### ISSUE THREAD

**Issue by anwfr** [Samourai-Wallet/samourai-wallet-android#70]
QRCode causes crash with low resolution devices (ie Jelly Pro 240x432px).

> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: com.samourai.wallet, PID: 2830
>                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.samourai.wallet/com.samourai.wallet.ReceiveActivity}: java.lang.IllegalArgumentException: Requested dimensions are too small: -220x-220
>                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
>                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
>                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
>                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
>                       at android.os.Handler.dispatchMessage(Handler.java:110)
>                       at android.os.Looper.loop(Looper.java:203)
>                       at android.app.ActivityThread.main(ActivityThread.java:6251)
>                       at java.lang.reflect.Method.invoke(Native Method)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
>                    Caused by: java.lang.IllegalArgumentException: Requested dimensions are too small: -220x-220
>                       at com.google.zxing.qrcode.QRCodeWriter.encode(QRCodeWriter.java:63)
>                       at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
>                       at com.google.zxing.client.android.encode.QRCodeEncoder.encodeAsBitmap(QRCodeEncoder.java:206)
>                       at com.samourai.wallet.ReceiveActivity.generateQRCode(ReceiveActivity.java:601)
>                       at com.samourai.wallet.ReceiveActivity.displayQRCode(ReceiveActivity.java:576)
>                       at com.samourai.wallet.ReceiveActivity.onCreate(ReceiveActivity.java:401)
>                       at android.app.Activity.performCreate(Activity.java:6666)
>                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
>                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
>                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789) 
>                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
>                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527) 
>                       at android.os.Handler.dispatchMessage(Handler.java:110) 
>                       at android.os.Looper.loop(Looper.java:203) 
>                       at android.app.ActivityThread.main(ActivityThread.java:6251) 
>                       at java.lang.reflect.Method.invoke(Native Method) 
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
>

**Comment by SamouraiDev** [comment]
Fixed in v0.97.10.

**Comment by SaiyajiiN** [comment]
app still crash when i try scan qr code.
