### ISSUE TITLE
Cannot restore wallet properly

### ISSUE THREAD

**Issue by darkwinry** [Samourai-Wallet/samourai-wallet-android#73]
I was trying to test the "restore wallet" functionality and it did not work.

Steps to replicate
1. Press "RESTORE WALLET" function
2. Entered the 12 word passphrase in the BIP39 passphrase field section press OK
3. The app takes me back to the Please select... RESTORE WALLET or CREATE WALLET modal popup.

**Comment by SamouraiDev** [comment]
Please contact support@samouraiwallet.com for all tech support issues. Thank you.
