### ISSUE TITLE
cannot edit credentials after scanning QRCode for payment

### ISSUE THREAD

**Issue by vv01f** [Samourai-Wallet/samourai-wallet-android#82]
Just recently I recognize that after scanning a QRCode I cannot

* change amount nor
* select/copy address any more

if I recall correctly that was working before as I used to copy the address to clipboard and edit the amount after setting the fee manually.

I just claim it's unexpected behavior from users view; plus not easy to circumvent. Possible solutions could be e.g. 

* make the user confirm he wants to edit and/or
* as a fallback copy the scanned address to clipboard

also relates to #39

**Comment by SamouraiDev** [comment]
If you scan a BIP21 URI then the data is effectively made read-only. If the elements are entered one at a time they will remain editable.
