### ISSUE TITLE
new transaction does not show a for a while

### ISSUE THREAD

**Issue by vv01f** [Samourai-Wallet/samourai-wallet-android#83]
just since the last 2 versions I recognize the sent tx not showing up.
also restarts dont help; it seems you list only what you find on the network.
I'd siggest to add the entry nevertheless so the sender knows (even if the wallet crashes, what it does usually rigth after sending) that the tx was sent **and** also she might have the chance to copy the raw tx/resend it.

**Comment by SamouraiDev** [comment]
Yes, this is an issue with our backend API and we are working on it. Please direct all support queries to support@samouraiwallet.com . Thank you.
