### ISSUE TITLE
Can't see balances if restore wallet using different PIN

### ISSUE THREAD

**Issue by notf0und** [Samourai-Wallet/samourai-wallet-android#84]
When I try to restore a wallet using a different PIN, I can't see the balances, then need to delete wallet and restore using the same 12 words, passphrase and same PIN. It's possible that different pin's generates different derivation path too?

**Comment by SamouraiDev** [comment]
No, not at all possible. PIN code has nothing to do with the wallet seed. This is simply a display issue which occurred when you changed PIN.

**Comment by notf0und** [comment]
I've not changed the PIN. I restored the wallet using the seed twice. 
The first one i used a different pin that when I created the wallet. No balances displayed.
The second time, I used the same PIN, and balances are displayed.
Repeated this procedure over different devices, with different seeds and same problem occurs.
Maybe it's a display issue as you told. This post its only to give you detailed information about the procedure to replicate it.

**Comment by samouraiwallet** [comment]
It sounds like when you are restoring you are either not using the same 12 words or you aren't using the correct passphrase. See this help article https://support.samourai.io/article/18-restore-your-samourai-wallet-with-your-secret-words - If you need help still email us on support@samouraiwallet.com

**Comment by SamouraiDev** [comment]
Please move this to support@samouraiwallet.com  Thank you.
