### ISSUE TITLE
Keyboard covers half of the Receive view

### ISSUE THREAD

**Issue by janklosowski** [Samourai-Wallet/samourai-wallet-android#85]
Nexus 5x / Android 8.1.0

Possible improvements:
1. Taping in the QR Code closes the keyboard.
2. The main content scrolls when is not fully visible.

![screenshot_20171226-204524](https://user-images.githubusercontent.com/916651/34363852-e4ba01fc-ea7f-11e7-9f91-3b41f8602f34.png)

**Comment by mb300sd** [comment]
Does your back button not close your keyboard? It has on every Android device I've used.

**Comment by janklosowski** [comment]
It does. However, in the case when not all content is visible, this pattern is usually complemented by an ability to scroll the view (2.)  or even to close the keyboard by taping the content (1.) e.g. Messenger does it. This is a UX improvement proposal.
