### ISSUE TITLE
Copy to clipboard dialog on press XPUB/YPUB text

### ISSUE THREAD

**Issue by notf0und** [Samourai-Wallet/samourai-wallet-android#88]
On some cell phones with a small screen it's really difficult to copy XPUB/YPUB text because first need to select all the text moving the cursors to select all the text. Maybe can be more easily if when text is pressed, appears a copy to clipboard dialog same as when a receiving address is pressed

**Comment by SamouraiDev** [comment]
OK, will look into this. Thank you.

**Comment by SamouraiDev** [comment]
This was included in a recent update.

**Comment by notf0und** [comment]
Tested and working.
