### ISSUE TITLE
Sign message with spended output addresses.

### ISSUE THREAD

**Issue by notf0und** [Samourai-Wallet/samourai-wallet-android#89]
That's necessary when you moved your funds and want to sing message with an zero-balance address. There are some airdrops that need a message signed from addresses that had funds before/until specific date, that isn't possible to do on samourai because only can sign messages using UTXO.

**Comment by SamouraiDev** [comment]
We are planning on more extensive UTXO/address/signing management in-app. In the meantime, any such address will require a small amount on it so it appears in the UTXO list. Once there, you can mark it as 'unspendable' so it remains in the UTXO list for any signing ops you may require.
