### ISSUE TITLE
Add 'rescan all' option to BIP47 Payment Channels

### ISSUE THREAD

**Issue by samouraiwallet** [Samourai-Wallet/samourai-wallet-android#9]
Currently users must rescan payment channels individually after they restore their wallet by seed. (if they don't rescan they are likely to see inconsistencies with their expected balance). The user should be able to rescan all payment channels at once, or even more ideally, Samourai should automatically rescan BIP47 Payment Channels after a recovery by seed.

**Comment by SamouraiDev** [comment]
Introduced in v0.82/85
