### ISSUE TITLE
iOS Version?

### ISSUE THREAD

**Issue by Conqu3rer** [Samourai-Wallet/samourai-wallet-android#91]
Hello, are you guys working on an iOS version? It would be a shame if the best bitcoin hot wallet does not come to iOS. :(

**Comment by SamouraiDev** [comment]
It's in the works, yes.

**Comment by Conqu3rer** [comment]
Thank you very much for this! Waiting for it eagerly.

**Comment by Revod** [comment]
Hey, any update? I mean... Any release date or something?
