### ISSUE TITLE
Feature request: Lightning network

### ISSUE THREAD

**Issue by carangel** [Samourai-Wallet/samourai-wallet-android#92]
With lightning network starting slowly to be rolled out, do Samourai have a plan for implementing it ?

**Comment by SamouraiDev** [comment]
We are looking at how LN can be used to enhance user privacy and will then determine how and when to fit it in to our roadmap.

**Comment by Camilojdl** [comment]
How you doing on the LN subject?
Have you seen this talk? Looks like an awesome UX .
4th talk - Patricia Estevao - Designing Lightning wallets for the Bitcoin user - https://youtu.be/XORDEX-RrAI?t=6033

**Comment by alexk111** [comment]
Any updates on this?

**Comment by heri16** [comment]
Is the Samourai dead?
