### ISSUE TITLE
Batched Sends

### ISSUE THREAD

**Issue by reardencode** [Samourai-Wallet/samourai-wallet-android#93]
It would be very useful, both for privacy enhancement, and for fee minimization to support sending Bitcoin to multiple outputs in a single transaction.

I think the UI could be something like:

```
Address
____________________________________
BTC _________  USD _________ Remove
Address
____________________________________
BTC _________  USD _________ Remove
Add an output
```

This would make it easier to use other privacy features like multiple change outputs and multiple inputs, because the higher fees would be mitigated.

**Comment by SamouraiDev** [comment]
We have already started work on this ;) and hope to be testing asap.

**Comment by reardencode** [comment]
That's fantastic!  I'd be happy to help with review or testing. I'm a decently experienced Java dev (no Android experience beyond ADB poking around though).

**Comment by notf0und** [comment]
This issue must be closed.
