### ISSUE TITLE
Add language setting support

### ISSUE THREAD

**Issue by eMaringolo** [Samourai-Wallet/samourai-wallet-android#97]
It would be great to be able to use the app in a different, supported, language other than the system's default (currently Samourai uses the operative system language for its UI).

There are some cases, where I have the OS in Spanish but still want to use the app in English.

The reasons for doing so are many, mainly because I'm more fluent with the terminology in English and/or because the Spanish translations are transliterated or not accurate.

**Comment by samouraiwallet** [comment]
Thanks for the feedback. We will look into better language handling overall for our 1.0 release and will keep this particular request in mind.

**Comment by eMaringolo** [comment]
Hey @samouraiwallet , meanwhile you can integrate this PR https://github.com/Samourai-Wallet/samourai-wallet-android/pull/117

The current Spanish translation is sub-standard and non-sensical in some cases.

Thank you very much.
