### ISSUE TITLE
Satoshis, bits, mbtcs

### ISSUE THREAD

**Issue by halfik** [Samourai-Wallet/samourai-wallet-android#99]
Can you bring back bits and mbtc?
Also satoshi would be nice.

**Comment by SamouraiDev** [comment]
The decision was made to remove denominations other than straightforward BTC.

**Comment by halfik** [comment]
You should rethink is. Most mobile wallets are used as hot wallets so people dont keep any significant amount of BTC there. Me and couple of my friends in example are keeping up to $300 in BTC. So with out option to denominate it to satoshis, bits or mbtc its problematic. You have to deal with all this 0.

**Comment by khaffner** [comment]
I would rather have support for more fiat currencies for now. I have looked at some of the code, it seems to me that the currently supported fiat currencies are hard coded. Could this perhaps be pulled dynamically from some exchange? Or at least make it easier to hard code support for more currencies?

**Comment by amicrod** [comment]
Fiat is dead.  We need to focus on the usability of bitcoin.  Simply google "round number bias".  Ignoring this basic tendency in humans will keep bitcoin from reaching max public utility and in the hands of speculators/computer geeks.  

To replicate this theory.. simply ask any person on the street whether they would like to get 0.002 of something or 20,000 of something...  (source: I work at an exchange)

**Comment by halfik** [comment]
We neeed other denominations except BTC. Its hard to not make a mistake when you have to send lets say 0.0000124. One zero can make a big differenece. Satoshis and bits should be implented.

**Comment by infernix** [comment]
> The decision was made to remove denominations other than straightforward BTC.

Why not make this a preference so the user can decide?

**Comment by SamouraiDev** [comment]
Bitcoin users use bitcoin denomination. We have no plans on bringing back mBits etc.

**Comment by halfik** [comment]
At least add satoshis. Its standard bitcoin denomination now used by LN.
